<?php

use Illuminate\Database\Seeder;
use App\Traits\Repositories;

class CityTableSeeder extends Seeder
{
    use Repositories;

    private $pbbrCities = [
        ['region_name' => 221, 'name' => 'Abucay'],
        ['region_name' => 221, 'name' => 'Bagac'],
        ['region_name' => 221, 'name' => 'Balanga City'],
        ['region_name' => 221, 'name' => 'Dinalupihan'],
        ['region_name' => 221, 'name' => 'Hermosa'],
        ['region_name' => 221, 'name' => 'Limay'],
        ['region_name' => 221, 'name' => 'Mariveles'],
        ['region_name' => 221, 'name' => 'Morong'],
        ['region_name' => 221, 'name' => 'Orani'],
        ['region_name' => 221, 'name' => 'Orion'],
        ['region_name' => 221, 'name' => 'Pilar'],
        ['region_name' => 221, 'name' => 'Samal'],
        ['region_name' => 221, 'name' => 'Angat'],
        ['region_name' => 221, 'name' => 'Balagtas (Bigaa)'],
        ['region_name' => 221, 'name' => 'Bocaue'],
        ['region_name' => 221, 'name' => 'Bulakan'],
        ['region_name' => 221, 'name' => 'Bustos'],
        ['region_name' => 221, 'name' => 'Calumpit'],
        ['region_name' => 221, 'name' => 'Doña Remedios Trinidad'],
        ['region_name' => 221, 'name' => 'Guiguinto'],
        ['region_name' => 221, 'name' => 'Hagonoy'],
        ['region_name' => 221, 'name' => 'Malolos City'],
        ['region_name' => 221, 'name' => 'Marilao'],
        ['region_name' => 221, 'name' => 'Pandi'],
        ['region_name' => 221, 'name' => 'Paombong'],
        ['region_name' => 221, 'name' => 'Plaridel'],
        ['region_name' => 221, 'name' => 'Pulilan'],
        ['region_name' => 221, 'name' => 'Santa Maria'],
        ['region_name' => 221, 'name' => 'Apalit'],
        ['region_name' => 221, 'name' => 'Bacolor'],
        ['region_name' => 221, 'name' => 'Floridablanca'],
        ['region_name' => 221, 'name' => 'Guagua'],
        ['region_name' => 221, 'name' => 'Lubao'],
        ['region_name' => 221, 'name' => 'Macabebe'],
        ['region_name' => 221, 'name' => 'San Simon'],
        ['region_name' => 221, 'name' => 'Santa Rita'],
        ['region_name' => 221, 'name' => 'Santo Tomas'],
        ['region_name' => 221, 'name' => 'Cabangan'],
        ['region_name' => 221, 'name' => 'Castillejos'],
        ['region_name' => 221, 'name' => 'Olongapo City'],
        ['region_name' => 221, 'name' => 'Subic'],
    ];

    private $pzbrCities = [
        ['region_name' => 222, 'name' => 'Agno'],
        ['region_name' => 222, 'name' => 'Aguilar'],
        ['region_name' => 222, 'name' => 'Alaminos City'],
        ['region_name' => 222, 'name' => 'Alcala'],
        ['region_name' => 222, 'name' => 'Anda'],
        ['region_name' => 222, 'name' => 'Asingan'],
        ['region_name' => 222, 'name' => 'Balungao'],
        ['region_name' => 222, 'name' => 'Bani'],
        ['region_name' => 222, 'name' => 'Basista'],
        ['region_name' => 222, 'name' => 'Bautista'],
        ['region_name' => 222, 'name' => 'Bayambang'],
        ['region_name' => 222, 'name' => 'Binalonan'],
        ['region_name' => 222, 'name' => 'Binmaley'],
        ['region_name' => 222, 'name' => 'Bolinao'],
        ['region_name' => 222, 'name' => 'Bugallon'],
        ['region_name' => 222, 'name' => 'Burgos'],
        ['region_name' => 222, 'name' => 'Calasiao'],
        ['region_name' => 222, 'name' => 'Dagupan City'],
        ['region_name' => 222, 'name' => 'Dasol'],
        ['region_name' => 222, 'name' => 'Infanta'],
        ['region_name' => 222, 'name' => 'Labrador'],
        ['region_name' => 222, 'name' => 'Laoac'],
        ['region_name' => 222, 'name' => 'Lingayen'],
        ['region_name' => 222, 'name' => 'Mabini'],
        ['region_name' => 222, 'name' => 'Malasiqui'],
        ['region_name' => 222, 'name' => 'Mangatarem'],
        ['region_name' => 222, 'name' => 'Natividad'],
        ['region_name' => 222, 'name' => 'Rosales'],
        ['region_name' => 222, 'name' => 'San Carlos City'],
        ['region_name' => 222, 'name' => 'San Jacinto'],
        ['region_name' => 222, 'name' => 'San Manuel'],
        ['region_name' => 222, 'name' => 'San Nicolas'],
        ['region_name' => 222, 'name' => 'San Quintin'],
        ['region_name' => 222, 'name' => 'Santa Barbara'],
        ['region_name' => 222, 'name' => 'Santa Maria'],
        ['region_name' => 222, 'name' => 'Santo Tomas'],
        ['region_name' => 222, 'name' => 'Sison'],
        ['region_name' => 222, 'name' => 'Sual'],
        ['region_name' => 222, 'name' => 'Tayug'],
        ['region_name' => 222, 'name' => 'Umingan'],
        ['region_name' => 222, 'name' => 'Urbiztondo'],
        ['region_name' => 222, 'name' => 'Urdaneta City'],
        ['region_name' => 222, 'name' => 'Villasis'],
        ['region_name' => 222, 'name' => 'Botolan'],
        ['region_name' => 222, 'name' => 'Candelaria'],
        ['region_name' => 222, 'name' => 'Iba'],
        ['region_name' => 222, 'name' => 'Masinloc'],
        ['region_name' => 222, 'name' => 'Palauig'],
        ['region_name' => 222, 'name' => 'San Antonio'],
        ['region_name' => 222, 'name' => 'San Felipe'],
        ['region_name' => 222, 'name' => 'San Marcelino'],
        ['region_name' => 222, 'name' => 'San Narciso'],
        ['region_name' => 222, 'name' => 'Santa Cruz'],
    ];

    private $cbrCities = [
        ['region_name' => 223, 'name' => 'Atok'],
        ['region_name' => 223, 'name' => 'Baguio City'],
        ['region_name' => 223, 'name' => 'Bakun'],
        ['region_name' => 223, 'name' => 'Bokod'],
        ['region_name' => 223, 'name' => 'Buguias'],
        ['region_name' => 223, 'name' => 'Itogon'],
        ['region_name' => 223, 'name' => 'Kabayan'],
        ['region_name' => 223, 'name' => 'Kapangan'],
        ['region_name' => 223, 'name' => 'Kibungan'],
        ['region_name' => 223, 'name' => 'La Trinidad'],
        ['region_name' => 223, 'name' => 'Mankayan'],
        ['region_name' => 223, 'name' => 'Sablan'],
        ['region_name' => 223, 'name' => 'Tuba'],
        ['region_name' => 223, 'name' => 'Tublay'],
        ['region_name' => 223, 'name' => 'Barlig'],
        ['region_name' => 223, 'name' => 'Bauko'],
        ['region_name' => 223, 'name' => 'Besao'],
        ['region_name' => 223, 'name' => 'Bontoc'],
        ['region_name' => 223, 'name' => 'Natonin'],
        ['region_name' => 223, 'name' => 'Paracelis'],
        ['region_name' => 223, 'name' => 'Sabangan'],
        ['region_name' => 223, 'name' => 'Sadanga'],
        ['region_name' => 223, 'name' => 'Sagada'],
        ['region_name' => 223, 'name' => 'Tadian'],
        ['region_name' => 223, 'name' => 'Agoo'],
        ['region_name' => 223, 'name' => 'Aringay'],
        ['region_name' => 223, 'name' => 'Bacnotan'],
        ['region_name' => 223, 'name' => 'Bagulin'],
        ['region_name' => 223, 'name' => 'Balaoan'],
        ['region_name' => 223, 'name' => 'Bangar'],
        ['region_name' => 223, 'name' => 'Bauang'],
        ['region_name' => 223, 'name' => 'Burgos'],
        ['region_name' => 223, 'name' => 'Caba'],
        ['region_name' => 223, 'name' => 'Luna'],
        ['region_name' => 223, 'name' => 'Naguilian'],
        ['region_name' => 223, 'name' => 'Pugo'],
        ['region_name' => 223, 'name' => 'Rosario'],
        ['region_name' => 223, 'name' => 'San Fernando City'],
        ['region_name' => 223, 'name' => 'San Gabriel'],
        ['region_name' => 223, 'name' => 'San Juan'],
        ['region_name' => 223, 'name' => 'Santo Tomas'],
        ['region_name' => 223, 'name' => 'Santol'],
        ['region_name' => 223, 'name' => 'Sudipen'],
        ['region_name' => 223, 'name' => 'Tubao'],
        ['region_name' => 223, 'name' => 'Manaoag'],
        ['region_name' => 223, 'name' => 'Mangaldan'],
        ['region_name' => 223, 'name' => 'Mapandan'],
        ['region_name' => 223, 'name' => 'Pozorrubio'],
        ['region_name' => 223, 'name' => 'San Fabian'],
    ];

    private $cvrCities = [
        ['region_name' => 224, 'name' => 'Aguinaldo'],
        ['region_name' => 224, 'name' => 'Alfonso Lista'],
        ['region_name' => 224, 'name' => 'Alfonso Lista (Potia)'],
        ['region_name' => 224, 'name' => 'Asipulo'],
        ['region_name' => 224, 'name' => 'Banaue'],
        ['region_name' => 224, 'name' => 'Hingyon'],
        ['region_name' => 224, 'name' => 'Hungduan'],
        ['region_name' => 224, 'name' => 'Kiangan'],
        ['region_name' => 224, 'name' => 'Lagawe'],
        ['region_name' => 224, 'name' => 'Lamut'],
        ['region_name' => 224, 'name' => 'Mayoyao'],
        ['region_name' => 224, 'name' => 'Tinoc'],
        ['region_name' => 224, 'name' => 'Balbalan'],
        ['region_name' => 224, 'name' => 'Lubuagan'],
        ['region_name' => 224, 'name' => 'Pasil'],
        ['region_name' => 224, 'name' => 'Pinukpuk'],
        ['region_name' => 224, 'name' => 'Rizal (Liwan)'],
        ['region_name' => 224, 'name' => 'Tabuk City'],
        ['region_name' => 224, 'name' => 'Tanudan'],
        ['region_name' => 224, 'name' => 'Tinglayan'],
        ['region_name' => 224, 'name' => 'Baggao'],
        ['region_name' => 224, 'name' => 'Ballesteros'],
        ['region_name' => 224, 'name' => 'Calayan'],
        ['region_name' => 224, 'name' => 'Camalaniugan'],
        ['region_name' => 224, 'name' => 'Iguig'],
        ['region_name' => 224, 'name' => 'Lasam'],
        ['region_name' => 224, 'name' => 'Peñablanca'],
        ['region_name' => 224, 'name' => 'Piat'],
        ['region_name' => 224, 'name' => 'Rizal'],
        ['region_name' => 224, 'name' => 'Santo Niño (Faire)'],
        ['region_name' => 224, 'name' => 'Solana'],
        ['region_name' => 224, 'name' => 'Tuao'],
        ['region_name' => 224, 'name' => 'Tuguegarao City'],
        ['region_name' => 224, 'name' => 'Alicia'],
        ['region_name' => 224, 'name' => 'Angadanan'],
        ['region_name' => 224, 'name' => 'Aurora'],
        ['region_name' => 224, 'name' => 'Benito Soliven'],
        ['region_name' => 224, 'name' => 'Burgos'],
        ['region_name' => 224, 'name' => 'Cabagan'],
        ['region_name' => 224, 'name' => 'Cabatuan'],
        ['region_name' => 224, 'name' => 'Cauayan City'],
        ['region_name' => 224, 'name' => 'Cordon'],
        ['region_name' => 224, 'name' => 'Delfin Albano (Magsaysay)'],
        ['region_name' => 224, 'name' => 'Dinapigue'],
        ['region_name' => 224, 'name' => 'Divilacan'],
        ['region_name' => 224, 'name' => 'Echague'],
        ['region_name' => 224, 'name' => 'Gamu'],
        ['region_name' => 224, 'name' => 'Ilagan City'],
        ['region_name' => 224, 'name' => 'Jones'],
        ['region_name' => 224, 'name' => 'Luna'],
        ['region_name' => 224, 'name' => 'Maconacon'],
        ['region_name' => 224, 'name' => 'Mallig'],
        ['region_name' => 224, 'name' => 'Naguilian'],
        ['region_name' => 224, 'name' => 'Palanan'],
        ['region_name' => 224, 'name' => 'Quezon'],
        ['region_name' => 224, 'name' => 'Quirino'],
        ['region_name' => 224, 'name' => 'Ramon'],
        ['region_name' => 224, 'name' => 'Reina Mercedes'],
        ['region_name' => 224, 'name' => 'Roxas'],
        ['region_name' => 224, 'name' => 'San Agustin'],
        ['region_name' => 224, 'name' => 'San Guillermo'],
        ['region_name' => 224, 'name' => 'San Isidro'],
        ['region_name' => 224, 'name' => 'San Manuel (Callang)'],
        ['region_name' => 224, 'name' => 'San Mariano'],
        ['region_name' => 224, 'name' => 'San Mateo'],
        ['region_name' => 224, 'name' => 'San Pablo'],
        ['region_name' => 224, 'name' => 'Santa Maria'],
        ['region_name' => 224, 'name' => 'Santiago City'],
        ['region_name' => 224, 'name' => 'Santo Tomas'],
        ['region_name' => 224, 'name' => 'Tumauini'],
        ['region_name' => 224, 'name' => 'Alfonso Castañeda'],
        ['region_name' => 224, 'name' => 'Ambaguio'],
        ['region_name' => 224, 'name' => 'Aritao'],
        ['region_name' => 224, 'name' => 'Bagabag'],
        ['region_name' => 224, 'name' => 'Bambang'],
        ['region_name' => 224, 'name' => 'Bayombong'],
        ['region_name' => 224, 'name' => 'Diadi'],
        ['region_name' => 224, 'name' => 'Dupax del Norte'],
        ['region_name' => 224, 'name' => 'Dupax del Sur'],
        ['region_name' => 224, 'name' => 'Kasibu'],
        ['region_name' => 224, 'name' => 'Kayapa'],
        ['region_name' => 224, 'name' => 'Santa Fe (Imugan)'],
        ['region_name' => 224, 'name' => 'Solano'],
        ['region_name' => 224, 'name' => 'Villaverde (Ibung)'],
        ['region_name' => 224, 'name' => 'Aglipay'],
        ['region_name' => 224, 'name' => 'Cabarroguis'],
        ['region_name' => 224, 'name' => 'Diffun'],
        ['region_name' => 224, 'name' => 'Maddela'],
        ['region_name' => 224, 'name' => 'Nagtipunan'],
        ['region_name' => 224, 'name' => 'Saguday'],
    ];

    private $neabrCities = [
        ['region_name' => 225, 'name' => 'Baler'],
        ['region_name' => 225, 'name' => 'Casiguran'],
        ['region_name' => 225, 'name' => 'Dilasag'],
        ['region_name' => 225, 'name' => 'Dinalungan'],
        ['region_name' => 225, 'name' => 'Dingalan'],
        ['region_name' => 225, 'name' => 'Dipaculao'],
        ['region_name' => 225, 'name' => 'Maria Aurora'],
        ['region_name' => 225, 'name' => 'San Luis'],
        ['region_name' => 225, 'name' => 'Baliuag'],
        ['region_name' => 225, 'name' => 'Norzagaray'],
        ['region_name' => 225, 'name' => 'San Ildefonso'],
        ['region_name' => 225, 'name' => 'San Miguel'],
        ['region_name' => 225, 'name' => 'San Rafael'],
        ['region_name' => 225, 'name' => 'Aliaga'],
        ['region_name' => 225, 'name' => 'Bongabon'],
        ['region_name' => 225, 'name' => 'Cabanatuan City'],
        ['region_name' => 225, 'name' => 'Cabiao'],
        ['region_name' => 225, 'name' => 'Carranglan'],
        ['region_name' => 225, 'name' => 'Cuyapo'],
        ['region_name' => 225, 'name' => 'Gabaldon (Bitulok & Sabani)'],
        ['region_name' => 225, 'name' => 'Gapan City'],
        ['region_name' => 225, 'name' => 'General Mamerto Natividad'],
        ['region_name' => 225, 'name' => 'General Tinio (Papaya)'],
        ['region_name' => 225, 'name' => 'Guimba'],
        ['region_name' => 225, 'name' => 'Jaen'],
        ['region_name' => 225, 'name' => 'Laur'],
        ['region_name' => 225, 'name' => 'Licab'],
        ['region_name' => 225, 'name' => 'Llanera'],
        ['region_name' => 225, 'name' => 'Lupao'],
        ['region_name' => 225, 'name' => 'Muñoz City'],
        ['region_name' => 225, 'name' => 'Nampicuan'],
        ['region_name' => 225, 'name' => 'Palayan City'],
        ['region_name' => 225, 'name' => 'Pantabangan'],
        ['region_name' => 225, 'name' => 'Peñaranda'],
        ['region_name' => 225, 'name' => 'Quezon'],
        ['region_name' => 225, 'name' => 'Rizal'],
        ['region_name' => 225, 'name' => 'San Antonio'],
        ['region_name' => 225, 'name' => 'San Isidro'],
        ['region_name' => 225, 'name' => 'San Jose City'],
        ['region_name' => 225, 'name' => 'San Leonardo'],
        ['region_name' => 225, 'name' => 'Santa Rosa'],
        ['region_name' => 225, 'name' => 'Santo Domingo'],
        ['region_name' => 225, 'name' => 'Talavera'],
        ['region_name' => 225, 'name' => 'Talugtug'],
        ['region_name' => 225, 'name' => 'Zaragoza'],
    ];

    private $mptbrCities = [
        ['region_name' => 226, 'name' => 'Angeles City'],
        ['region_name' => 226, 'name' => 'Arayat'],
        ['region_name' => 226, 'name' => 'Candaba'],
        ['region_name' => 226, 'name' => 'Mabalacat City'],
        ['region_name' => 226, 'name' => 'Magalang'],
        ['region_name' => 226, 'name' => 'Masantol'],
        ['region_name' => 226, 'name' => 'Mexico'],
        ['region_name' => 226, 'name' => 'Minalin'],
        ['region_name' => 226, 'name' => 'Porac'],
        ['region_name' => 226, 'name' => 'San Fernando City'],
        ['region_name' => 226, 'name' => 'San Luis'],
        ['region_name' => 226, 'name' => 'Santa Ana'],
        ['region_name' => 226, 'name' => 'Sasmuan'],
        ['region_name' => 226, 'name' => 'Anao'],
        ['region_name' => 226, 'name' => 'Bamban'],
        ['region_name' => 226, 'name' => 'Camiling'],
        ['region_name' => 226, 'name' => 'Capas'],
        ['region_name' => 226, 'name' => 'Concepcion'],
        ['region_name' => 226, 'name' => 'Gerona'],
        ['region_name' => 226, 'name' => 'La Paz'],
        ['region_name' => 226, 'name' => 'Mayantoc'],
        ['region_name' => 226, 'name' => 'Moncada'],
        ['region_name' => 226, 'name' => 'Paniqui'],
        ['region_name' => 226, 'name' => 'Pura'],
        ['region_name' => 226, 'name' => 'Ramos'],
        ['region_name' => 226, 'name' => 'San Clemente'],
        ['region_name' => 226, 'name' => 'San Jose'],
        ['region_name' => 226, 'name' => 'San Manuel'],
        ['region_name' => 226, 'name' => 'Santa Ignacia'],
        ['region_name' => 226, 'name' => 'Tarlac City City'],
        ['region_name' => 226, 'name' => 'Victoria'],
    ];

    private $ibrCities =[
        ['region_name' => 227, 'name' => 'Bangued'],
        ['region_name' => 227, 'name' => 'Boliney'],
        ['region_name' => 227, 'name' => 'Bucay'],
        ['region_name' => 227, 'name' => 'Bucloc'],
        ['region_name' => 227, 'name' => 'Daguioman'],
        ['region_name' => 227, 'name' => 'Danglas'],
        ['region_name' => 227, 'name' => 'Dolores'],
        ['region_name' => 227, 'name' => 'La Paz'],
        ['region_name' => 227, 'name' => 'Lacub'],
        ['region_name' => 227, 'name' => 'Lagangilang'],
        ['region_name' => 227, 'name' => 'Lagayan'],
        ['region_name' => 227, 'name' => 'Langiden'],
        ['region_name' => 227, 'name' => 'Licuan-Baay (Licuan)'],
        ['region_name' => 227, 'name' => 'Luba'],
        ['region_name' => 227, 'name' => 'Malibcong'],
        ['region_name' => 227, 'name' => 'Manabo'],
        ['region_name' => 227, 'name' => 'Peñarrubia'],
        ['region_name' => 227, 'name' => 'Pidigan'],
        ['region_name' => 227, 'name' => 'Pilar'],
        ['region_name' => 227, 'name' => 'Sallapadan'],
        ['region_name' => 227, 'name' => 'San Isidro'],
        ['region_name' => 227, 'name' => 'San Juan'],
        ['region_name' => 227, 'name' => 'San Quintin'],
        ['region_name' => 227, 'name' => 'Tayum'],
        ['region_name' => 227, 'name' => 'Tineg'],
        ['region_name' => 227, 'name' => 'Tubo'],
        ['region_name' => 227, 'name' => 'Villaviciosa'],
        ['region_name' => 227, 'name' => 'Calanasan'],
        ['region_name' => 227, 'name' => 'Conner'],
        ['region_name' => 227, 'name' => 'Flora'],
        ['region_name' => 227, 'name' => 'Kabugao'],
        ['region_name' => 227, 'name' => 'Luna'],
        ['region_name' => 227, 'name' => 'Pudtol'],
        ['region_name' => 227, 'name' => 'Santa Marcela'],
        ['region_name' => 227, 'name' => 'Adams'],
        ['region_name' => 227, 'name' => 'Bacarra'],
        ['region_name' => 227, 'name' => 'Badoc'],
        ['region_name' => 227, 'name' => 'Bangui'],
        ['region_name' => 227, 'name' => 'Banna (Espiritu)'],
        ['region_name' => 227, 'name' => 'Batac City'],
        ['region_name' => 227, 'name' => 'Burgos'],
        ['region_name' => 227, 'name' => 'Carasi'],
        ['region_name' => 227, 'name' => 'Currimao'],
        ['region_name' => 227, 'name' => 'Dingras'],
        ['region_name' => 227, 'name' => 'Dumalneg'],
        ['region_name' => 227, 'name' => 'Laoag City'],
        ['region_name' => 227, 'name' => 'Marcos'],
        ['region_name' => 227, 'name' => 'Nueva Era'],
        ['region_name' => 227, 'name' => 'Pagudpud'],
        ['region_name' => 227, 'name' => 'Paoay'],
        ['region_name' => 227, 'name' => 'Pasuquin'],
        ['region_name' => 227, 'name' => 'Piddig'],
        ['region_name' => 227, 'name' => 'Pinili'],
        ['region_name' => 227, 'name' => 'San Nicolas'],
        ['region_name' => 227, 'name' => 'Sarrat'],
        ['region_name' => 227, 'name' => 'Solsona'],
        ['region_name' => 227, 'name' => 'Vintar'],
        ['region_name' => 227, 'name' => 'Alilem'],
        ['region_name' => 227, 'name' => 'Banayoyo'],
        ['region_name' => 227, 'name' => 'Bantay'],
        ['region_name' => 227, 'name' => 'Cabugao'],
        ['region_name' => 227, 'name' => 'Candon City'],
        ['region_name' => 227, 'name' => 'Caoayan'],
        ['region_name' => 227, 'name' => 'Cervantes'],
        ['region_name' => 227, 'name' => 'Galimuyod'],
        ['region_name' => 227, 'name' => 'Gregorio del Pilar (Concepcion)'],
        ['region_name' => 227, 'name' => 'Lidlidda'],
        ['region_name' => 227, 'name' => 'Magsingal'],
        ['region_name' => 227, 'name' => 'Nagbukel'],
        ['region_name' => 227, 'name' => 'Narvacan'],
        ['region_name' => 227, 'name' => 'Quirino (Angkaki)'],
        ['region_name' => 227, 'name' => 'Salcedo (Baugen)'],
        ['region_name' => 227, 'name' => 'San Emilio'],
        ['region_name' => 227, 'name' => 'San Esteban'],
        ['region_name' => 227, 'name' => 'San Ildefonso'],
        ['region_name' => 227, 'name' => 'San Juan (Lapog)'],
        ['region_name' => 227, 'name' => 'San Vicente'],
        ['region_name' => 227, 'name' => 'Santa'],
        ['region_name' => 227, 'name' => 'Santa Catalina'],
        ['region_name' => 227, 'name' => 'Santa Cruz'],
        ['region_name' => 227, 'name' => 'Santa Lucia'],
        ['region_name' => 227, 'name' => 'Santa Maria'],
        ['region_name' => 227, 'name' => 'Santiago'],
        ['region_name' => 227, 'name' => 'Santo Domingo'],
        ['region_name' => 227, 'name' => 'Sigay'],
        ['region_name' => 227, 'name' => 'Sinait'],
        ['region_name' => 227, 'name' => 'Sugpon'],
        ['region_name' => 227, 'name' => 'Suyo'],
        ['region_name' => 227, 'name' => 'Tagudin'],
        ['region_name' => 227, 'name' => 'Vigan City'],
        ['region_name' => 227, 'name' => 'Basco'],
        ['region_name' => 227, 'name' => 'Itbayat'],
        ['region_name' => 227, 'name' => 'Ivana'],
        ['region_name' => 227, 'name' => 'Mahatao'],
        ['region_name' => 227, 'name' => 'Sabtang'],
        ['region_name' => 227, 'name' => 'Uyugan'],
        ['region_name' => 227, 'name' => 'Abulug'],
        ['region_name' => 227, 'name' => 'Alcala'],
        ['region_name' => 227, 'name' => 'Allacapan'],
        ['region_name' => 227, 'name' => 'Amulung'],
        ['region_name' => 227, 'name' => 'Aparri'],
        ['region_name' => 227, 'name' => 'Buguey'],
        ['region_name' => 227, 'name' => 'Claveria'],
        ['region_name' => 227, 'name' => 'Enrile'],
        ['region_name' => 227, 'name' => 'Gattaran'],
        ['region_name' => 227, 'name' => 'Gonzaga'],
        ['region_name' => 227, 'name' => 'Lal-lo'],
        ['region_name' => 227, 'name' => 'Pamplona'],
        ['region_name' => 227, 'name' => 'Sanchez-Mira'],
        ['region_name' => 227, 'name' => 'Santa Ana'],
        ['region_name' => 227, 'name' => 'Santa Praxedes'],
        ['region_name' => 227, 'name' => 'Santa Teresita'],
    ];

    private $nwgmaCities = [
        ['region_name' => 321, 'name' => 'Caloocan City'],
        ['region_name' => 321, 'name' => 'Navotas City'],
    ];

    private $cgmaCities = [
        ['region_name' => 322, 'name' => 'City of San Juan'],
        ['region_name' => 322, 'name' => 'Marikina City'],
        ['region_name' => 322, 'name' => 'Quezon City'],
        ['region_name' => 322, 'name' => 'Rodriguez (Montalban)'],
        ['region_name' => 322, 'name' => 'San Mateo'],
    ];

    private $wgmaCities = [
        ['region_name' => 323, 'name' => 'City of Manila - Binondo'],
        ['region_name' => 323, 'name' => 'City of Manila - Ermita'],
        ['region_name' => 323, 'name' => 'City of Manila - Intramuros'],
        ['region_name' => 323, 'name' => 'City of Manila - Malate'],
        ['region_name' => 323, 'name' => 'City of Manila - Paco'],
        ['region_name' => 323, 'name' => 'City of Manila - Pandacan'],
        ['region_name' => 323, 'name' => 'City of Manila - Port Area'],
        ['region_name' => 323, 'name' => 'City of Manila - Quiapo'],
        ['region_name' => 323, 'name' => 'City of Manila - Sampaloc'],
        ['region_name' => 323, 'name' => 'City of Manila - San Miguel'],
        ['region_name' => 323, 'name' => 'City of Manila - San Nicolas'],
        ['region_name' => 323, 'name' => 'City of Manila - Santa Ana'],
        ['region_name' => 323, 'name' => 'City of Manila - Santa Cruz'],
        ['region_name' => 323, 'name' => 'City of Manila - Tondo'],
        ['region_name' => 323, 'name' => 'Makati City'],
    ];

    private $egmaCities = [
        ['region_name' => 324, 'name' => 'Mandaluyong City'],
        ['region_name' => 324, 'name' => 'Pasig City'],
        ['region_name' => 324, 'name' => 'Pateros'],
        ['region_name' => 324, 'name' => 'Angono'],
        ['region_name' => 324, 'name' => 'Antipolo City'],
        ['region_name' => 324, 'name' => 'Baras'],
        ['region_name' => 324, 'name' => 'Binangonan'],
        ['region_name' => 324, 'name' => 'Cainta'],
        ['region_name' => 324, 'name' => 'Cardona'],
        ['region_name' => 324, 'name' => 'Jalajala'],
        ['region_name' => 324, 'name' => 'Morong'],
        ['region_name' => 324, 'name' => 'Pililla'],
        ['region_name' => 324, 'name' => 'Tanay'],
        ['region_name' => 324, 'name' => 'Taytay'],
        ['region_name' => 324, 'name' => 'Teresa'],
    ];

    private $ngmaCities = [
        ['region_name' => 325, 'name' => 'Malabon City'],
        ['region_name' => 325, 'name' => 'Valenzuela City'],
        ['region_name' => 325, 'name' => 'Meycauayan City'],
        ['region_name' => 325, 'name' => 'Obando'],
        ['region_name' => 325, 'name' => 'San Jose del Monte City'],
    ];

    private $sgmaCities = [
        ['region_name' => 326, 'name' => 'Las Piñas City'],
        ['region_name' => 326, 'name' => 'Muntinlupa City'],
        ['region_name' => 326, 'name' => 'Parañaque City'],
        ['region_name' => 326, 'name' => 'Pasay City'],
        ['region_name' => 326, 'name' => 'Taguig City'],
    ];

    private $qmbrCities = [
        ['region_name' => 421, 'name' => 'Alaminos'],
        ['region_name' => 421, 'name' => 'Rizal'],
        ['region_name' => 421, 'name' => 'San Pablo City'],
        ['region_name' => 421, 'name' => 'Agdangan'],
        ['region_name' => 421, 'name' => 'Alabat'],
        ['region_name' => 421, 'name' => 'Atimonan'],
        ['region_name' => 421, 'name' => 'Buenavista'],
        ['region_name' => 421, 'name' => 'Calauag'],
        ['region_name' => 421, 'name' => 'Candelaria'],
        ['region_name' => 421, 'name' => 'Catanauan'],
        ['region_name' => 421, 'name' => 'Dolores'],
        ['region_name' => 421, 'name' => 'General Luna'],
        ['region_name' => 421, 'name' => 'Guinayangan'],
        ['region_name' => 421, 'name' => 'Gumaca'],
        ['region_name' => 421, 'name' => 'Lopez'],
        ['region_name' => 421, 'name' => 'Lucban'],
        ['region_name' => 421, 'name' => 'Lucena City'],
        ['region_name' => 421, 'name' => 'Macalelon'],
        ['region_name' => 421, 'name' => 'Mauban'],
        ['region_name' => 421, 'name' => 'Mulanay'],
        ['region_name' => 421, 'name' => 'Padre Burgos'],
        ['region_name' => 421, 'name' => 'Pagbilao'],
        ['region_name' => 421, 'name' => 'Perez'],
        ['region_name' => 421, 'name' => 'Pitogo'],
        ['region_name' => 421, 'name' => 'Plaridel'],
        ['region_name' => 421, 'name' => 'Quezon'],
        ['region_name' => 421, 'name' => 'Sampaloc'],
        ['region_name' => 421, 'name' => 'San Andres'],
        ['region_name' => 421, 'name' => 'San Antonio'],
        ['region_name' => 421, 'name' => 'San Francisco (Aurora)'],
        ['region_name' => 421, 'name' => 'San Narciso'],
        ['region_name' => 421, 'name' => 'Sariaya'],
        ['region_name' => 421, 'name' => 'Tayabas City'],
        ['region_name' => 421, 'name' => 'Tiaong'],
        ['region_name' => 421, 'name' => 'Unisan'],
        ['region_name' => 421, 'name' => 'Boac'],
        ['region_name' => 421, 'name' => 'Gasan'],
        ['region_name' => 421, 'name' => 'Mogpog'],
        ['region_name' => 421, 'name' => 'Santa Cruz'],
        ['region_name' => 421, 'name' => 'Torrijos'],
    ];

    private $cbbrCities = [
        ['region_name' => 422, 'name' => 'Balayan'],
        ['region_name' => 422, 'name' => 'Calaca'],
        ['region_name' => 422, 'name' => 'Calatagan'],
        ['region_name' => 422, 'name' => 'Lemery'],
        ['region_name' => 422, 'name' => 'Lian'],
        ['region_name' => 422, 'name' => 'Nasugbu'],
        ['region_name' => 422, 'name' => 'San Juan'],
        ['region_name' => 422, 'name' => 'San Luis'],
        ['region_name' => 422, 'name' => 'San Nicolas'],
        ['region_name' => 422, 'name' => 'Santa Teresita'],
        ['region_name' => 422, 'name' => 'Taal'],
        ['region_name' => 422, 'name' => 'Tuy'],
        ['region_name' => 422, 'name' => 'Alfonso'],
        ['region_name' => 422, 'name' => 'Amadeo'],
        ['region_name' => 422, 'name' => 'Dasmariñas City'],
        ['region_name' => 422, 'name' => 'General Mariano Alvarez'],
        ['region_name' => 422, 'name' => 'General Trias City'],
        ['region_name' => 422, 'name' => 'Imus City'],
        ['region_name' => 422, 'name' => 'Indang'],
        ['region_name' => 422, 'name' => 'Magallanes'],
        ['region_name' => 422, 'name' => 'Maragondon'],
        ['region_name' => 422, 'name' => 'Mendez (Mendez-Nuñez)'],
        ['region_name' => 422, 'name' => 'Naic'],
        ['region_name' => 422, 'name' => 'Silang'],
        ['region_name' => 422, 'name' => 'Tagaytay City'],
        ['region_name' => 422, 'name' => 'Tanza'],
        ['region_name' => 422, 'name' => 'Ternate'],
        ['region_name' => 422, 'name' => 'Trece Martires City'],
    ];

    private $nbbrCities = [
        ['region_name' => 423, 'name' => 'Tagkawayan'],
        ['region_name' => 423, 'name' => 'Libon'],
        ['region_name' => 423, 'name' => 'Ligao City'],
        ['region_name' => 423, 'name' => 'Oas'],
        ['region_name' => 423, 'name' => 'Pio Duran'],
        ['region_name' => 423, 'name' => 'Polangui'],
        ['region_name' => 423, 'name' => 'Basud'],
        ['region_name' => 423, 'name' => 'Capalonga'],
        ['region_name' => 423, 'name' => 'Daet'],
        ['region_name' => 423, 'name' => 'Jose Panganiban'],
        ['region_name' => 423, 'name' => 'Labo'],
        ['region_name' => 423, 'name' => 'Mercedes'],
        ['region_name' => 423, 'name' => 'Paracale'],
        ['region_name' => 423, 'name' => 'San Lorenzo Ruiz (Imelda)'],
        ['region_name' => 423, 'name' => 'San Vicente'],
        ['region_name' => 423, 'name' => 'Santa Elena'],
        ['region_name' => 423, 'name' => 'Talisay'],
        ['region_name' => 423, 'name' => 'Vinzons'],
        ['region_name' => 423, 'name' => 'Baao'],
        ['region_name' => 423, 'name' => 'Balatan'],
        ['region_name' => 423, 'name' => 'Bato'],
        ['region_name' => 423, 'name' => 'Bombon'],
        ['region_name' => 423, 'name' => 'Buhi'],
        ['region_name' => 423, 'name' => 'Bula'],
        ['region_name' => 423, 'name' => 'Cabusao'],
        ['region_name' => 423, 'name' => 'Calabanga'],
        ['region_name' => 423, 'name' => 'Camaligan'],
        ['region_name' => 423, 'name' => 'Canaman'],
        ['region_name' => 423, 'name' => 'Caramoan'],
        ['region_name' => 423, 'name' => 'Del Gallego'],
        ['region_name' => 423, 'name' => 'Gainza'],
        ['region_name' => 423, 'name' => 'Garchitorena'],
        ['region_name' => 423, 'name' => 'Goa'],
        ['region_name' => 423, 'name' => 'Iriga City'],
        ['region_name' => 423, 'name' => 'Lagonoy'],
        ['region_name' => 423, 'name' => 'Libmanan'],
        ['region_name' => 423, 'name' => 'Lupi'],
        ['region_name' => 423, 'name' => 'Magarao'],
        ['region_name' => 423, 'name' => 'Milaor'],
        ['region_name' => 423, 'name' => 'Minalabac'],
        ['region_name' => 423, 'name' => 'Nabua'],
        ['region_name' => 423, 'name' => 'Naga City'],
        ['region_name' => 423, 'name' => 'Ocampo'],
        ['region_name' => 423, 'name' => 'Pamplona'],
        ['region_name' => 423, 'name' => 'Pasacao'],
        ['region_name' => 423, 'name' => 'Pili'],
        ['region_name' => 423, 'name' => 'Presentacion (Parubcan)'],
        ['region_name' => 423, 'name' => 'Ragay'],
        ['region_name' => 423, 'name' => 'Sagñay'],
        ['region_name' => 423, 'name' => 'San Fernando'],
        ['region_name' => 423, 'name' => 'San Jose'],
        ['region_name' => 423, 'name' => 'Sipocot'],
        ['region_name' => 423, 'name' => 'Siruma'],
        ['region_name' => 423, 'name' => 'Tigaon'],
        ['region_name' => 423, 'name' => 'Tinambac'],
    ];

    private $cpbrCities = [
        ['region_name' => 424, 'name' => 'Bacoor City'],
        ['region_name' => 424, 'name' => 'Cavite City'],
        ['region_name' => 424, 'name' => 'Kawit'],
        ['region_name' => 424, 'name' => 'Noveleta'],
        ['region_name' => 424, 'name' => 'Rosario'],
        ['region_name' => 424, 'name' => 'Aborlan'],
        ['region_name' => 424, 'name' => 'Agutaya'],
        ['region_name' => 424, 'name' => 'Araceli'],
        ['region_name' => 424, 'name' => 'Balabac'],
        ['region_name' => 424, 'name' => 'Bataraza'],
        ['region_name' => 424, 'name' => 'Brooke\'s Point'],
        ['region_name' => 424, 'name' => 'Busuanga'],
        ['region_name' => 424, 'name' => 'Cagayancillo'],
        ['region_name' => 424, 'name' => 'Coron'],
        ['region_name' => 424, 'name' => 'Culion'],
        ['region_name' => 424, 'name' => 'Cuyo'],
        ['region_name' => 424, 'name' => 'Dumaran'],
        ['region_name' => 424, 'name' => 'El Nido (Bacuit)'],
        ['region_name' => 424, 'name' => 'Kalayaan'],
        ['region_name' => 424, 'name' => 'Linapacan'],
        ['region_name' => 424, 'name' => 'Magsaysay'],
        ['region_name' => 424, 'name' => 'Narra'],
        ['region_name' => 424, 'name' => 'Puerto Princesa City'],
        ['region_name' => 424, 'name' => 'Quezon'],
        ['region_name' => 424, 'name' => 'Rizal (Marcos)'],
        ['region_name' => 424, 'name' => 'Roxas'],
        ['region_name' => 424, 'name' => 'San Vicente'],
        ['region_name' => 424, 'name' => 'Sofronio Española'],
        ['region_name' => 424, 'name' => 'Taytay'],
    ];

    private $lpbrCities = [
        ['region_name' => 425, 'name' => 'Carmona'],
        ['region_name' => 425, 'name' => 'General Emilio Aguinaldo'],
        ['region_name' => 425, 'name' => 'Bay'],
        ['region_name' => 425, 'name' => 'Biñan City'],
        ['region_name' => 425, 'name' => 'Cabuyao City'],
        ['region_name' => 425, 'name' => 'Calamba City'],
        ['region_name' => 425, 'name' => 'Calauan'],
        ['region_name' => 425, 'name' => 'Cavinti'],
        ['region_name' => 425, 'name' => 'Famy'],
        ['region_name' => 425, 'name' => 'Kalayaan'],
        ['region_name' => 425, 'name' => 'Liliw'],
        ['region_name' => 425, 'name' => 'Los Baños'],
        ['region_name' => 425, 'name' => 'Luisiana'],
        ['region_name' => 425, 'name' => 'Lumban'],
        ['region_name' => 425, 'name' => 'Mabitac'],
        ['region_name' => 425, 'name' => 'Magdalena'],
        ['region_name' => 425, 'name' => 'Majayjay'],
        ['region_name' => 425, 'name' => 'Nagcarlan'],
        ['region_name' => 425, 'name' => 'Paete'],
        ['region_name' => 425, 'name' => 'Pagsanjan'],
        ['region_name' => 425, 'name' => 'Pakil'],
        ['region_name' => 425, 'name' => 'Pangil'],
        ['region_name' => 425, 'name' => 'Pila'],
        ['region_name' => 425, 'name' => 'San Pedro City'],
        ['region_name' => 425, 'name' => 'Santa Cruz'],
        ['region_name' => 425, 'name' => 'Santa Maria'],
        ['region_name' => 425, 'name' => 'Santa Rosa City'],
        ['region_name' => 425, 'name' => 'Siniloan'],
        ['region_name' => 425, 'name' => 'Victoria'],
        ['region_name' => 425, 'name' => 'Burdeos'],
        ['region_name' => 425, 'name' => 'General Nakar'],
        ['region_name' => 425, 'name' => 'Infanta'],
        ['region_name' => 425, 'name' => 'Jomalig'],
        ['region_name' => 425, 'name' => 'Panukulan'],
        ['region_name' => 425, 'name' => 'Patnanungan'],
        ['region_name' => 425, 'name' => 'Polillo'],
        ['region_name' => 425, 'name' => 'Real'],
    ];

    private $bmrbrCities = [
        ['region_name' => 426, 'name' => 'Agoncillo'],
        ['region_name' => 426, 'name' => 'Alitagtag'],
        ['region_name' => 426, 'name' => 'Balete'],
        ['region_name' => 426, 'name' => 'Batangas City'],
        ['region_name' => 426, 'name' => 'Bauan'],
        ['region_name' => 426, 'name' => 'Cuenca'],
        ['region_name' => 426, 'name' => 'Ibaan'],
        ['region_name' => 426, 'name' => 'Laurel'],
        ['region_name' => 426, 'name' => 'Lipa City'],
        ['region_name' => 426, 'name' => 'Lobo'],
        ['region_name' => 426, 'name' => 'Mabini'],
        ['region_name' => 426, 'name' => 'Malvar'],
        ['region_name' => 426, 'name' => 'Mataasnakahoy'],
        ['region_name' => 426, 'name' => 'Padre Garcia'],
        ['region_name' => 426, 'name' => 'Rosario'],
        ['region_name' => 426, 'name' => 'San Jose'],
        ['region_name' => 426, 'name' => 'San Pascual'],
        ['region_name' => 426, 'name' => 'Santo Tomas City'],
        ['region_name' => 426, 'name' => 'Talisay'],
        ['region_name' => 426, 'name' => 'Tanauan City'],
        ['region_name' => 426, 'name' => 'Taysan'],
        ['region_name' => 426, 'name' => 'Tingloy'],
        ['region_name' => 426, 'name' => 'Abra de Ilog'],
        ['region_name' => 426, 'name' => 'Calintaan'],
        ['region_name' => 426, 'name' => 'Looc'],
        ['region_name' => 426, 'name' => 'Lubang'],
        ['region_name' => 426, 'name' => 'Magsaysay'],
        ['region_name' => 426, 'name' => 'Mamburao'],
        ['region_name' => 426, 'name' => 'Paluan'],
        ['region_name' => 426, 'name' => 'Rizal'],
        ['region_name' => 426, 'name' => 'Sablayan'],
        ['region_name' => 426, 'name' => 'Santa Cruz'],
        ['region_name' => 426, 'name' => 'Baco'],
        ['region_name' => 426, 'name' => 'Bansud'],
        ['region_name' => 426, 'name' => 'Bongabong'],
        ['region_name' => 426, 'name' => 'Bulalacao (San Pedro)'],
        ['region_name' => 426, 'name' => 'Calapan City'],
        ['region_name' => 426, 'name' => 'Gloria'],
        ['region_name' => 426, 'name' => 'Mansalay'],
        ['region_name' => 426, 'name' => 'Naujan'],
        ['region_name' => 426, 'name' => 'Pinamalayan'],
        ['region_name' => 426, 'name' => 'Pola'],
        ['region_name' => 426, 'name' => 'Puerto Galera'],
        ['region_name' => 426, 'name' => 'Roxas'],
        ['region_name' => 426, 'name' => 'San Teodoro'],
        ['region_name' => 426, 'name' => 'Socorro'],
        ['region_name' => 426, 'name' => 'Victoria'],
        ['region_name' => 426, 'name' => 'Alcantara'],
        ['region_name' => 426, 'name' => 'Banton (Jones)'],
        ['region_name' => 426, 'name' => 'Cajidiocan'],
        ['region_name' => 426, 'name' => 'Calatrava'],
        ['region_name' => 426, 'name' => 'Concepcion'],
        ['region_name' => 426, 'name' => 'Corcuera'],
        ['region_name' => 426, 'name' => 'Ferrol'],
        ['region_name' => 426, 'name' => 'Magdiwang'],
        ['region_name' => 426, 'name' => 'Odiongan'],
        ['region_name' => 426, 'name' => 'Romblon'],
        ['region_name' => 426, 'name' => 'San Agustin'],
        ['region_name' => 426, 'name' => 'San Andres'],
        ['region_name' => 426, 'name' => 'San Fernando'],
        ['region_name' => 426, 'name' => 'Santa Fe'],
        ['region_name' => 426, 'name' => 'Santa Maria (Imelda)'],
    ];

    private $sbbrCities = [
        ['region_name' => 427, 'name' => 'Bacacay'],
        ['region_name' => 427, 'name' => 'Camalig'],
        ['region_name' => 427, 'name' => 'Daraga (Locsin)'],
        ['region_name' => 427, 'name' => 'Guinobatan'],
        ['region_name' => 427, 'name' => 'Jovellar'],
        ['region_name' => 427, 'name' => 'Legazpi City'],
        ['region_name' => 427, 'name' => 'Malilipot'],
        ['region_name' => 427, 'name' => 'Malinao'],
        ['region_name' => 427, 'name' => 'Manito'],
        ['region_name' => 427, 'name' => 'Rapu-Rapu'],
        ['region_name' => 427, 'name' => 'Santo Domingo'],
        ['region_name' => 427, 'name' => 'Tabaco City'],
        ['region_name' => 427, 'name' => 'Tiwi'],
        ['region_name' => 427, 'name' => 'Bagamanoc'],
        ['region_name' => 427, 'name' => 'Baras'],
        ['region_name' => 427, 'name' => 'Bato'],
        ['region_name' => 427, 'name' => 'Caramoran'],
        ['region_name' => 427, 'name' => 'Gigmoto'],
        ['region_name' => 427, 'name' => 'Pandan'],
        ['region_name' => 427, 'name' => 'Panganiban (Payo)'],
        ['region_name' => 427, 'name' => 'San Andres (Calolbon)'],
        ['region_name' => 427, 'name' => 'San Miguel'],
        ['region_name' => 427, 'name' => 'Viga'],
        ['region_name' => 427, 'name' => 'Virac'],
        ['region_name' => 427, 'name' => 'Aroroy'],
        ['region_name' => 427, 'name' => 'Baleno'],
        ['region_name' => 427, 'name' => 'Balud'],
        ['region_name' => 427, 'name' => 'Batuan'],
        ['region_name' => 427, 'name' => 'Cataingan'],
        ['region_name' => 427, 'name' => 'Cawayan'],
        ['region_name' => 427, 'name' => 'Claveria'],
        ['region_name' => 427, 'name' => 'Dimasalang'],
        ['region_name' => 427, 'name' => 'Esperanza'],
        ['region_name' => 427, 'name' => 'Mandaon'],
        ['region_name' => 427, 'name' => 'Masbate City'],
        ['region_name' => 427, 'name' => 'Milagros'],
        ['region_name' => 427, 'name' => 'Mobo'],
        ['region_name' => 427, 'name' => 'Monreal'],
        ['region_name' => 427, 'name' => 'Palanas'],
        ['region_name' => 427, 'name' => 'Pio V. Corpuz (Limbuhan)'],
        ['region_name' => 427, 'name' => 'Placer'],
        ['region_name' => 427, 'name' => 'San Fernando'],
        ['region_name' => 427, 'name' => 'San Jacinto'],
        ['region_name' => 427, 'name' => 'San Pascual'],
        ['region_name' => 427, 'name' => 'Uson'],
        ['region_name' => 427, 'name' => 'Barcelona'],
        ['region_name' => 427, 'name' => 'Bulan'],
        ['region_name' => 427, 'name' => 'Bulusan'],
        ['region_name' => 427, 'name' => 'Casiguran'],
        ['region_name' => 427, 'name' => 'Castilla'],
        ['region_name' => 427, 'name' => 'Donsol'],
        ['region_name' => 427, 'name' => 'Gubat'],
        ['region_name' => 427, 'name' => 'Irosin'],
        ['region_name' => 427, 'name' => 'Juban'],
        ['region_name' => 427, 'name' => 'Magallanes'],
        ['region_name' => 427, 'name' => 'Matnog'],
        ['region_name' => 427, 'name' => 'Pilar'],
        ['region_name' => 427, 'name' => 'Prieto Diaz'],
        ['region_name' => 427, 'name' => 'Santa Magdalena'],
        ['region_name' => 427, 'name' => 'Sorsogon City'],
    ];

    private $norbrCities = [
        ['region_name' => 521, 'name' => 'Hinoba-an (Asia)'],
        ['region_name' => 521, 'name' => 'Salvador Benedicto'],
        ['region_name' => 521, 'name' => 'San Carlos City'],
        ['region_name' => 521, 'name' => 'Toboso'],
        ['region_name' => 521, 'name' => 'Amlan (Ayuquitan)'],
        ['region_name' => 521, 'name' => 'Ayungon'],
        ['region_name' => 521, 'name' => 'Bacong'],
        ['region_name' => 521, 'name' => 'Bais City'],
        ['region_name' => 521, 'name' => 'Basay'],
        ['region_name' => 521, 'name' => 'Bayawan City (Tulong)'],
        ['region_name' => 521, 'name' => 'Bindoy (Payabon)'],
        ['region_name' => 521, 'name' => 'Canlaon City'],
        ['region_name' => 521, 'name' => 'Dauin'],
        ['region_name' => 521, 'name' => 'Dumaguete City'],
        ['region_name' => 521, 'name' => 'Guihulngan City'],
        ['region_name' => 521, 'name' => 'Jimalalud'],
        ['region_name' => 521, 'name' => 'La Libertad'],
        ['region_name' => 521, 'name' => 'Mabinay'],
        ['region_name' => 521, 'name' => 'Manjuyod'],
        ['region_name' => 521, 'name' => 'Pamplona'],
        ['region_name' => 521, 'name' => 'San Jose'],
        ['region_name' => 521, 'name' => 'Santa Catalina'],
        ['region_name' => 521, 'name' => 'Siaton'],
        ['region_name' => 521, 'name' => 'Sibulan'],
        ['region_name' => 521, 'name' => 'Tanjay City'],
        ['region_name' => 521, 'name' => 'Tayasan'],
        ['region_name' => 521, 'name' => 'Valencia (Luzurriaga)'],
        ['region_name' => 521, 'name' => 'Vallehermoso'],
        ['region_name' => 521, 'name' => 'Zamboanguita'],
        ['region_name' => 521, 'name' => 'Enrique Villanueva'],
        ['region_name' => 521, 'name' => 'Larena'],
        ['region_name' => 521, 'name' => 'Lazi'],
        ['region_name' => 521, 'name' => 'Maria'],
        ['region_name' => 521, 'name' => 'San Juan'],
        ['region_name' => 521, 'name' => 'Siquijor'],
    ];

    private $nocbrCities = [
        ['region_name' => 522, 'name' => 'Bacolod City'],
        ['region_name' => 522, 'name' => 'Bago City'],
        ['region_name' => 522, 'name' => 'Binalbagan'],
        ['region_name' => 522, 'name' => 'Cadiz City'],
        ['region_name' => 522, 'name' => 'Calatrava'],
        ['region_name' => 522, 'name' => 'Candoni'],
        ['region_name' => 522, 'name' => 'Cauayan'],
        ['region_name' => 522, 'name' => 'Enrique B. Magalona (Saravia)'],
        ['region_name' => 522, 'name' => 'Escalante City'],
        ['region_name' => 522, 'name' => 'Himamaylan City'],
        ['region_name' => 522, 'name' => 'Hinigaran'],
        ['region_name' => 522, 'name' => 'Ilog'],
        ['region_name' => 522, 'name' => 'Isabela'],
        ['region_name' => 522, 'name' => 'Kabankalan City'],
        ['region_name' => 522, 'name' => 'La Carlota City'],
        ['region_name' => 522, 'name' => 'La Castellana'],
        ['region_name' => 522, 'name' => 'Manapla'],
        ['region_name' => 522, 'name' => 'Moises Padilla (Magallon)'],
        ['region_name' => 522, 'name' => 'Murcia'],
        ['region_name' => 522, 'name' => 'Pontevedra'],
        ['region_name' => 522, 'name' => 'Pulupandan'],
        ['region_name' => 522, 'name' => 'Sagay City'],
        ['region_name' => 522, 'name' => 'San Enrique'],
        ['region_name' => 522, 'name' => 'Silay City'],
        ['region_name' => 522, 'name' => 'Sipalay City'],
        ['region_name' => 522, 'name' => 'Talisay City'],
        ['region_name' => 522, 'name' => 'Valladolid'],
        ['region_name' => 522, 'name' => 'Victorias City'],
    ];

    private $igbrCities = [
        ['region_name' => 523, 'name' => 'Buenavista'],
        ['region_name' => 523, 'name' => 'Jordan'],
        ['region_name' => 523, 'name' => 'Nueva Valencia'],
        ['region_name' => 523, 'name' => 'San Lorenzo'],
        ['region_name' => 523, 'name' => 'Sibunag'],
        ['region_name' => 523, 'name' => 'Ajuy'],
        ['region_name' => 523, 'name' => 'Alimodian'],
        ['region_name' => 523, 'name' => 'Anilao'],
        ['region_name' => 523, 'name' => 'Badiangan'],
        ['region_name' => 523, 'name' => 'Balasan'],
        ['region_name' => 523, 'name' => 'Banate'],
        ['region_name' => 523, 'name' => 'Barotac Nuevo'],
        ['region_name' => 523, 'name' => 'Barotac Viejo'],
        ['region_name' => 523, 'name' => 'Batad'],
        ['region_name' => 523, 'name' => 'Bingawan'],
        ['region_name' => 523, 'name' => 'Cabatuan'],
        ['region_name' => 523, 'name' => 'Calinog'],
        ['region_name' => 523, 'name' => 'Carles'],
        ['region_name' => 523, 'name' => 'Concepcion'],
        ['region_name' => 523, 'name' => 'Dingle'],
        ['region_name' => 523, 'name' => 'Dueñas'],
        ['region_name' => 523, 'name' => 'Dumangas'],
        ['region_name' => 523, 'name' => 'Estancia'],
        ['region_name' => 523, 'name' => 'Guimbal'],
        ['region_name' => 523, 'name' => 'Igbaras'],
        ['region_name' => 523, 'name' => 'Iloilo City'],
        ['region_name' => 523, 'name' => 'Janiuay'],
        ['region_name' => 523, 'name' => 'Lambunao'],
        ['region_name' => 523, 'name' => 'Leganes'],
        ['region_name' => 523, 'name' => 'Lemery'],
        ['region_name' => 523, 'name' => 'Leon'],
        ['region_name' => 523, 'name' => 'Maasin'],
        ['region_name' => 523, 'name' => 'Miagao'],
        ['region_name' => 523, 'name' => 'Mina'],
        ['region_name' => 523, 'name' => 'New Lucena'],
        ['region_name' => 523, 'name' => 'Oton'],
        ['region_name' => 523, 'name' => 'Passi City'],
        ['region_name' => 523, 'name' => 'Pavia'],
        ['region_name' => 523, 'name' => 'Pototan'],
        ['region_name' => 523, 'name' => 'San Dionisio'],
        ['region_name' => 523, 'name' => 'San Enrique'],
        ['region_name' => 523, 'name' => 'San Joaquin'],
        ['region_name' => 523, 'name' => 'San Miguel'],
        ['region_name' => 523, 'name' => 'San Rafael'],
        ['region_name' => 523, 'name' => 'Santa Barbara'],
        ['region_name' => 523, 'name' => 'Sara'],
        ['region_name' => 523, 'name' => 'Tigbauan'],
        ['region_name' => 523, 'name' => 'Tubungan'],
        ['region_name' => 523, 'name' => 'Zarraga'],
    ];

    private $acabrCities = [
        ['region_name' => 524, 'name' => 'Altavas'],
        ['region_name' => 524, 'name' => 'Balete'],
        ['region_name' => 524, 'name' => 'Banga'],
        ['region_name' => 524, 'name' => 'Batan'],
        ['region_name' => 524, 'name' => 'Buruanga'],
        ['region_name' => 524, 'name' => 'Ibajay'],
        ['region_name' => 524, 'name' => 'Kalibo'],
        ['region_name' => 524, 'name' => 'Lezo'],
        ['region_name' => 524, 'name' => 'Libacao'],
        ['region_name' => 524, 'name' => 'Madalag'],
        ['region_name' => 524, 'name' => 'Makato'],
        ['region_name' => 524, 'name' => 'Malay'],
        ['region_name' => 524, 'name' => 'Malinao'],
        ['region_name' => 524, 'name' => 'Nabas'],
        ['region_name' => 524, 'name' => 'New Washington'],
        ['region_name' => 524, 'name' => 'Numancia'],
        ['region_name' => 524, 'name' => 'Tangalan'],
        ['region_name' => 524, 'name' => 'Anini-y'],
        ['region_name' => 524, 'name' => 'Barbaza'],
        ['region_name' => 524, 'name' => 'Belison'],
        ['region_name' => 524, 'name' => 'Bugasong'],
        ['region_name' => 524, 'name' => 'Caluya'],
        ['region_name' => 524, 'name' => 'Culasi'],
        ['region_name' => 524, 'name' => 'Hamtic'],
        ['region_name' => 524, 'name' => 'Laua-an'],
        ['region_name' => 524, 'name' => 'Libertad'],
        ['region_name' => 524, 'name' => 'Pandan'],
        ['region_name' => 524, 'name' => 'Patnongon'],
        ['region_name' => 524, 'name' => 'San Jose de Buenavista'],
        ['region_name' => 524, 'name' => 'San Remigio'],
        ['region_name' => 524, 'name' => 'Sebaste'],
        ['region_name' => 524, 'name' => 'Sibalom'],
        ['region_name' => 524, 'name' => 'Tibiao'],
        ['region_name' => 524, 'name' => 'Tobias Fornier (Dao)'],
        ['region_name' => 524, 'name' => 'Valderrama'],
        ['region_name' => 524, 'name' => 'Cuartero'],
        ['region_name' => 524, 'name' => 'Dao'],
        ['region_name' => 524, 'name' => 'Dumalag'],
        ['region_name' => 524, 'name' => 'Dumarao'],
        ['region_name' => 524, 'name' => 'Ivisan'],
        ['region_name' => 524, 'name' => 'Jamindan'],
        ['region_name' => 524, 'name' => 'Ma-ayon'],
        ['region_name' => 524, 'name' => 'Mambusao'],
        ['region_name' => 524, 'name' => 'Panay'],
        ['region_name' => 524, 'name' => 'Panitan'],
        ['region_name' => 524, 'name' => 'Pilar'],
        ['region_name' => 524, 'name' => 'Pontevedra'],
        ['region_name' => 524, 'name' => 'President Roxas'],
        ['region_name' => 524, 'name' => 'Roxas City City'],
        ['region_name' => 524, 'name' => 'Sapian'],
        ['region_name' => 524, 'name' => 'Sigma'],
        ['region_name' => 524, 'name' => 'Tapaz'],
    ];

    private $cvnbrCities = [
        ['region_name' => 621, 'name' => 'Aloguinsan'],
        ['region_name' => 621, 'name' => 'Asturias'],
        ['region_name' => 621, 'name' => 'Balamban'],
        ['region_name' => 621, 'name' => 'Bantayan'],
        ['region_name' => 621, 'name' => 'Bogo City'],
        ['region_name' => 621, 'name' => 'Borbon'],
        ['region_name' => 621, 'name' => 'Carmen'],
        ['region_name' => 621, 'name' => 'Catmon'],
        ['region_name' => 621, 'name' => 'Compostela'],
        ['region_name' => 621, 'name' => 'Consolacion'],
        ['region_name' => 621, 'name' => 'Cordova'],
        ['region_name' => 621, 'name' => 'Daanbantayan'],
        ['region_name' => 621, 'name' => 'Danao City'],
        ['region_name' => 621, 'name' => 'Lapu-Lapu City (Opon)'],
        ['region_name' => 621, 'name' => 'Liloan'],
        ['region_name' => 621, 'name' => 'Madridejos'],
        ['region_name' => 621, 'name' => 'Mandaue City'],
        ['region_name' => 621, 'name' => 'Medellin'],
        ['region_name' => 621, 'name' => 'Pilar'],
        ['region_name' => 621, 'name' => 'Pinamungajan'],
        ['region_name' => 621, 'name' => 'Poro'],
        ['region_name' => 621, 'name' => 'San Francisco'],
        ['region_name' => 621, 'name' => 'San Remigio'],
        ['region_name' => 621, 'name' => 'Santa Fe'],
        ['region_name' => 621, 'name' => 'Sogod'],
        ['region_name' => 621, 'name' => 'Tabogon'],
        ['region_name' => 621, 'name' => 'Tabuelan'],
        ['region_name' => 621, 'name' => 'Toledo City'],
        ['region_name' => 621, 'name' => 'Tuburan'],
        ['region_name' => 621, 'name' => 'Tudela'],
    ];

    private $evlbrCities = [
        ['region_name' => 622, 'name' => 'Almeria'],
        ['region_name' => 622, 'name' => 'Biliran'],
        ['region_name' => 622, 'name' => 'Cabucgayan'],
        ['region_name' => 622, 'name' => 'Caibiran'],
        ['region_name' => 622, 'name' => 'Culaba'],
        ['region_name' => 622, 'name' => 'Kawayan'],
        ['region_name' => 622, 'name' => 'Maripipi'],
        ['region_name' => 622, 'name' => 'Naval'],
        ['region_name' => 622, 'name' => 'Abuyog'],
        ['region_name' => 622, 'name' => 'Alangalang'],
        ['region_name' => 622, 'name' => 'Albuera'],
        ['region_name' => 622, 'name' => 'Babatngon'],
        ['region_name' => 622, 'name' => 'Barugo'],
        ['region_name' => 622, 'name' => 'Bato'],
        ['region_name' => 622, 'name' => 'Baybay City'],
        ['region_name' => 622, 'name' => 'Burauen'],
        ['region_name' => 622, 'name' => 'Calubian'],
        ['region_name' => 622, 'name' => 'Capoocan'],
        ['region_name' => 622, 'name' => 'Carigara'],
        ['region_name' => 622, 'name' => 'Dagami'],
        ['region_name' => 622, 'name' => 'Dulag'],
        ['region_name' => 622, 'name' => 'Hilongos'],
        ['region_name' => 622, 'name' => 'Hindang'],
        ['region_name' => 622, 'name' => 'Inopacan'],
        ['region_name' => 622, 'name' => 'Isabel'],
        ['region_name' => 622, 'name' => 'Jaro'],
        ['region_name' => 622, 'name' => 'Javier (Bugho)'],
        ['region_name' => 622, 'name' => 'Julita'],
        ['region_name' => 622, 'name' => 'Kananga'],
        ['region_name' => 622, 'name' => 'La Paz'],
        ['region_name' => 622, 'name' => 'Leyte'],
        ['region_name' => 622, 'name' => 'MacArthur'],
        ['region_name' => 622, 'name' => 'Mahaplag'],
        ['region_name' => 622, 'name' => 'Matag-ob'],
        ['region_name' => 622, 'name' => 'Matalom'],
        ['region_name' => 622, 'name' => 'Mayorga'],
        ['region_name' => 622, 'name' => 'Merida'],
        ['region_name' => 622, 'name' => 'Ormoc City'],
        ['region_name' => 622, 'name' => 'Palo'],
        ['region_name' => 622, 'name' => 'Palompon'],
        ['region_name' => 622, 'name' => 'Pastrana'],
        ['region_name' => 622, 'name' => 'San Isidro'],
        ['region_name' => 622, 'name' => 'San Miguel'],
        ['region_name' => 622, 'name' => 'Santa Fe'],
        ['region_name' => 622, 'name' => 'Tabango'],
        ['region_name' => 622, 'name' => 'Tabontabon'],
        ['region_name' => 622, 'name' => 'Tacloban City'],
        ['region_name' => 622, 'name' => 'Tanauan'],
        ['region_name' => 622, 'name' => 'Tolosa'],
        ['region_name' => 622, 'name' => 'Tunga'],
        ['region_name' => 622, 'name' => 'Villaba'],
        ['region_name' => 622, 'name' => 'Anahawan'],
        ['region_name' => 622, 'name' => 'Bontoc'],
        ['region_name' => 622, 'name' => 'Hinunangan'],
        ['region_name' => 622, 'name' => 'Hinundayan'],
        ['region_name' => 622, 'name' => 'Libagon'],
        ['region_name' => 622, 'name' => 'Liloan'],
        ['region_name' => 622, 'name' => 'Limasawa'],
        ['region_name' => 622, 'name' => 'Maasin City'],
        ['region_name' => 622, 'name' => 'Macrohon'],
        ['region_name' => 622, 'name' => 'Malitbog'],
        ['region_name' => 622, 'name' => 'Padre Burgos'],
        ['region_name' => 622, 'name' => 'Pintuyan'],
        ['region_name' => 622, 'name' => 'Saint Bernard'],
        ['region_name' => 622, 'name' => 'San Francisco'],
        ['region_name' => 622, 'name' => 'San Juan (Cabalian)'],
        ['region_name' => 622, 'name' => 'San Ricardo'],
        ['region_name' => 622, 'name' => 'Silago'],
        ['region_name' => 622, 'name' => 'Sogod'],
        ['region_name' => 622, 'name' => 'Tomas Oppus'],
    ];

    private $cvsbrCities = [
        ['region_name' => 623, 'name' => 'Alburquerque'],
        ['region_name' => 623, 'name' => 'Alicia'],
        ['region_name' => 623, 'name' => 'Anda'],
        ['region_name' => 623, 'name' => 'Antequera'],
        ['region_name' => 623, 'name' => 'Baclayon'],
        ['region_name' => 623, 'name' => 'Balilihan'],
        ['region_name' => 623, 'name' => 'Batuan'],
        ['region_name' => 623, 'name' => 'Bien Unido'],
        ['region_name' => 623, 'name' => 'Bilar'],
        ['region_name' => 623, 'name' => 'Buenavista'],
        ['region_name' => 623, 'name' => 'Calape'],
        ['region_name' => 623, 'name' => 'Candijay'],
        ['region_name' => 623, 'name' => 'Carmen'],
        ['region_name' => 623, 'name' => 'Catigbian'],
        ['region_name' => 623, 'name' => 'Clarin'],
        ['region_name' => 623, 'name' => 'Corella'],
        ['region_name' => 623, 'name' => 'Cortes'],
        ['region_name' => 623, 'name' => 'Dagohoy'],
        ['region_name' => 623, 'name' => 'Danao'],
        ['region_name' => 623, 'name' => 'Dauis'],
        ['region_name' => 623, 'name' => 'Dimiao'],
        ['region_name' => 623, 'name' => 'Duero'],
        ['region_name' => 623, 'name' => 'Garcia Hernandez'],
        ['region_name' => 623, 'name' => 'Getafe'],
        ['region_name' => 623, 'name' => 'Guindulman'],
        ['region_name' => 623, 'name' => 'Inabanga'],
        ['region_name' => 623, 'name' => 'Jagna'],
        ['region_name' => 623, 'name' => 'Lila'],
        ['region_name' => 623, 'name' => 'Loay'],
        ['region_name' => 623, 'name' => 'Loboc'],
        ['region_name' => 623, 'name' => 'Loon'],
        ['region_name' => 623, 'name' => 'Mabini'],
        ['region_name' => 623, 'name' => 'Maribojoc'],
        ['region_name' => 623, 'name' => 'Panglao'],
        ['region_name' => 623, 'name' => 'Pilar'],
        ['region_name' => 623, 'name' => 'President Carlos P. Garcia (Pitogo)'],
        ['region_name' => 623, 'name' => 'Sagbayan (Borja)'],
        ['region_name' => 623, 'name' => 'San Isidro'],
        ['region_name' => 623, 'name' => 'San Miguel'],
        ['region_name' => 623, 'name' => 'Sevilla'],
        ['region_name' => 623, 'name' => 'Sierra Bullones'],
        ['region_name' => 623, 'name' => 'Sikatuna'],
        ['region_name' => 623, 'name' => 'Tagbilaran City'],
        ['region_name' => 623, 'name' => 'Talibon'],
        ['region_name' => 623, 'name' => 'Trinidad'],
        ['region_name' => 623, 'name' => 'Tubigon'],
        ['region_name' => 623, 'name' => 'Ubay'],
        ['region_name' => 623, 'name' => 'Valencia'],
        ['region_name' => 623, 'name' => 'Alcantara'],
        ['region_name' => 623, 'name' => 'Alcoy'],
        ['region_name' => 623, 'name' => 'Alegria'],
        ['region_name' => 623, 'name' => 'Argao'],
        ['region_name' => 623, 'name' => 'Badian'],
        ['region_name' => 623, 'name' => 'Barili'],
        ['region_name' => 623, 'name' => 'Boljoon'],
        ['region_name' => 623, 'name' => 'Carcar City'],
        ['region_name' => 623, 'name' => 'Cebu City'],
        ['region_name' => 623, 'name' => 'Dalaguete'],
        ['region_name' => 623, 'name' => 'Dumanjug'],
        ['region_name' => 623, 'name' => 'Ginatilan'],
        ['region_name' => 623, 'name' => 'Malabuyoc'],
        ['region_name' => 623, 'name' => 'Minglanilla'],
        ['region_name' => 623, 'name' => 'Moalboal'],
        ['region_name' => 623, 'name' => 'Naga City'],
        ['region_name' => 623, 'name' => 'Oslob'],
        ['region_name' => 623, 'name' => 'Ronda'],
        ['region_name' => 623, 'name' => 'Samboan'],
        ['region_name' => 623, 'name' => 'San Fernando'],
        ['region_name' => 623, 'name' => 'Santander'],
        ['region_name' => 623, 'name' => 'Sibonga'],
        ['region_name' => 623, 'name' => 'Talisay City'],
    ];

    private $evsbrCities = [
        ['region_name' => 625, 'name' => 'Arteche'],
        ['region_name' => 625, 'name' => 'Balangiga'],
        ['region_name' => 625, 'name' => 'Balangkayan'],
        ['region_name' => 625, 'name' => 'Borongan City'],
        ['region_name' => 625, 'name' => 'Can-avid'],
        ['region_name' => 625, 'name' => 'Dolores'],
        ['region_name' => 625, 'name' => 'General MacArthur'],
        ['region_name' => 625, 'name' => 'Giporlos'],
        ['region_name' => 625, 'name' => 'Guiuan'],
        ['region_name' => 625, 'name' => 'Hernani'],
        ['region_name' => 625, 'name' => 'Jipapad'],
        ['region_name' => 625, 'name' => 'Lawaan'],
        ['region_name' => 625, 'name' => 'Llorente'],
        ['region_name' => 625, 'name' => 'Maslog'],
        ['region_name' => 625, 'name' => 'Maydolong'],
        ['region_name' => 625, 'name' => 'Mercedes'],
        ['region_name' => 625, 'name' => 'Oras'],
        ['region_name' => 625, 'name' => 'Quinapondan'],
        ['region_name' => 625, 'name' => 'Salcedo'],
        ['region_name' => 625, 'name' => 'San Julian'],
        ['region_name' => 625, 'name' => 'San Policarpo'],
        ['region_name' => 625, 'name' => 'Sulat'],
        ['region_name' => 625, 'name' => 'Taft'],
        ['region_name' => 625, 'name' => 'Allen'],
        ['region_name' => 625, 'name' => 'Biri'],
        ['region_name' => 625, 'name' => 'Bobon'],
        ['region_name' => 625, 'name' => 'Capul'],
        ['region_name' => 625, 'name' => 'Catarman'],
        ['region_name' => 625, 'name' => 'Catubig'],
        ['region_name' => 625, 'name' => 'Gamay'],
        ['region_name' => 625, 'name' => 'Laoang'],
        ['region_name' => 625, 'name' => 'Lapinig'],
        ['region_name' => 625, 'name' => 'Las Navas'],
        ['region_name' => 625, 'name' => 'Lavezares'],
        ['region_name' => 625, 'name' => 'Lope de Vega'],
        ['region_name' => 625, 'name' => 'Mapanas'],
        ['region_name' => 625, 'name' => 'Mondragon'],
        ['region_name' => 625, 'name' => 'Palapag'],
        ['region_name' => 625, 'name' => 'Pambujan'],
        ['region_name' => 625, 'name' => 'Rosario'],
        ['region_name' => 625, 'name' => 'San Antonio'],
        ['region_name' => 625, 'name' => 'San Isidro'],
        ['region_name' => 625, 'name' => 'San Jose'],
        ['region_name' => 625, 'name' => 'San Roque'],
        ['region_name' => 625, 'name' => 'San Vicente'],
        ['region_name' => 625, 'name' => 'Silvino Lobos'],
        ['region_name' => 625, 'name' => 'Victoria'],
        ['region_name' => 625, 'name' => 'Almagro'],
        ['region_name' => 625, 'name' => 'Basey'],
        ['region_name' => 625, 'name' => 'Calbayog City'],
        ['region_name' => 625, 'name' => 'Calbiga'],
        ['region_name' => 625, 'name' => 'Catbalogan City'],
        ['region_name' => 625, 'name' => 'Daram'],
        ['region_name' => 625, 'name' => 'Gandara'],
        ['region_name' => 625, 'name' => 'Hinabangan'],
        ['region_name' => 625, 'name' => 'Jiabong'],
        ['region_name' => 625, 'name' => 'Marabut'],
        ['region_name' => 625, 'name' => 'Matuguinao'],
        ['region_name' => 625, 'name' => 'Motiong'],
        ['region_name' => 625, 'name' => 'Pagsanghan'],
        ['region_name' => 625, 'name' => 'Paranas (Wright)'],
        ['region_name' => 625, 'name' => 'Pinabacdao'],
        ['region_name' => 625, 'name' => 'San Jorge'],
        ['region_name' => 625, 'name' => 'San Jose de Buan'],
        ['region_name' => 625, 'name' => 'San Sebastian'],
        ['region_name' => 625, 'name' => 'Santa Margarita'],
        ['region_name' => 625, 'name' => 'Santa Rita'],
        ['region_name' => 625, 'name' => 'Santo Niño'],
        ['region_name' => 625, 'name' => 'Tagapul-an'],
        ['region_name' => 625, 'name' => 'Talalora'],
        ['region_name' => 625, 'name' => 'Tarangnan'],
        ['region_name' => 625, 'name' => 'Villareal'],
        ['region_name' => 625, 'name' => 'Zumarraga'],
    ];

    private $mdavCities = [
        ['region_name' => 721, 'name' => 'Davao City'],
    ];

    private $socCities = [
        ['region_name' => 722, 'name' => 'Alabel'],
        ['region_name' => 722, 'name' => 'Glan'],
        ['region_name' => 722, 'name' => 'Kiamba'],
        ['region_name' => 722, 'name' => 'Maasim'],
        ['region_name' => 722, 'name' => 'Maitum'],
        ['region_name' => 722, 'name' => 'Malapatan'],
        ['region_name' => 722, 'name' => 'Malungon'],
        ['region_name' => 722, 'name' => 'Banga'],
        ['region_name' => 722, 'name' => 'General Santos City (Dadiangas)'],
        ['region_name' => 722, 'name' => 'Koronadal City'],
        ['region_name' => 722, 'name' => 'Lake Sebu'],
        ['region_name' => 722, 'name' => 'Norala'],
        ['region_name' => 722, 'name' => 'Polomolok'],
        ['region_name' => 722, 'name' => 'Santo Niño'],
        ['region_name' => 722, 'name' => 'Surallah'],
        ['region_name' => 722, 'name' => 'Tampakan'],
        ['region_name' => 722, 'name' => 'Tantangan'],
        ['region_name' => 722, 'name' => 'T\'Boli'],
        ['region_name' => 722, 'name' => 'Tupi'],
        ['region_name' => 722, 'name' => 'President Quirino'],
        ['region_name' => 722, 'name' => 'Senator Ninoy Aquino'],
        ['region_name' => 722, 'name' => 'Tacurong City'],

    ];

    private $nminCities = [
        ['region_name' => 723, 'name' => 'Baungon'],
        ['region_name' => 723, 'name' => 'Cabanglasan'],
        ['region_name' => 723, 'name' => 'Damulog'],
        ['region_name' => 723, 'name' => 'Dangcagan'],
        ['region_name' => 723, 'name' => 'Don Carlos'],
        ['region_name' => 723, 'name' => 'Impasugong'],
        ['region_name' => 723, 'name' => 'Kadingilan'],
        ['region_name' => 723, 'name' => 'Kalilangan'],
        ['region_name' => 723, 'name' => 'Kibawe'],
        ['region_name' => 723, 'name' => 'Kitaotao'],
        ['region_name' => 723, 'name' => 'Lantapan'],
        ['region_name' => 723, 'name' => 'Libona'],
        ['region_name' => 723, 'name' => 'Malaybalay City'],
        ['region_name' => 723, 'name' => 'Malitbog'],
        ['region_name' => 723, 'name' => 'Manolo Fortich'],
        ['region_name' => 723, 'name' => 'Maramag'],
        ['region_name' => 723, 'name' => 'Pangantucan'],
        ['region_name' => 723, 'name' => 'Quezon'],
        ['region_name' => 723, 'name' => 'San Fernando'],
        ['region_name' => 723, 'name' => 'Sumilao'],
        ['region_name' => 723, 'name' => 'Talakag'],
        ['region_name' => 723, 'name' => 'Valencia City'],
        ['region_name' => 723, 'name' => 'Catarman'],
        ['region_name' => 723, 'name' => 'Guinsiliban'],
        ['region_name' => 723, 'name' => 'Mahinog'],
        ['region_name' => 723, 'name' => 'Mambajao'],
        ['region_name' => 723, 'name' => 'Sagay'],
        ['region_name' => 723, 'name' => 'Cagayan de Oro City'],
        ['region_name' => 723, 'name' => 'Claveria'],
        ['region_name' => 723, 'name' => 'El Salvador City'],
        ['region_name' => 723, 'name' => 'Gingoog City'],
        ['region_name' => 723, 'name' => 'Gitagum'],
        ['region_name' => 723, 'name' => 'Initao'],
        ['region_name' => 723, 'name' => 'Jasaan'],
        ['region_name' => 723, 'name' => 'Kinoguitan'],
        ['region_name' => 723, 'name' => 'Lagonglong'],
        ['region_name' => 723, 'name' => 'Laguindingan'],
        ['region_name' => 723, 'name' => 'Libertad'],
        ['region_name' => 723, 'name' => 'Lugait'],
        ['region_name' => 723, 'name' => 'Magsaysay (Linugos)'],
        ['region_name' => 723, 'name' => 'Manticao'],
        ['region_name' => 723, 'name' => 'Medina'],
        ['region_name' => 723, 'name' => 'Naawan'],
        ['region_name' => 723, 'name' => 'Opol'],
        ['region_name' => 723, 'name' => 'Salay'],
        ['region_name' => 723, 'name' => 'Sugbongcogon'],
        ['region_name' => 723, 'name' => 'Tagoloan'],
        ['region_name' => 723, 'name' => 'Talisayan'],
        ['region_name' => 723, 'name' => 'Villanueva'],
        ['region_name' => 723, 'name' => 'Tagoloan II'],
        ['region_name' => 723, 'name' => 'Wao'],
    ];

    private $zamCities = [
        ['region_name' => 724, 'name' => 'Baliguian'],
        ['region_name' => 724, 'name' => 'Dapitan City'],
        ['region_name' => 724, 'name' => 'Dipolog City'],
        ['region_name' => 724, 'name' => 'Godod'],
        ['region_name' => 724, 'name' => 'Gutalac'],
        ['region_name' => 724, 'name' => 'Jose Dalman (Ponot)'],
        ['region_name' => 724, 'name' => 'Kalawit'],
        ['region_name' => 724, 'name' => 'Katipunan'],
        ['region_name' => 724, 'name' => 'La Libertad'],
        ['region_name' => 724, 'name' => 'Labason'],
        ['region_name' => 724, 'name' => 'Leon B. Postigo (Bacungan)'],
        ['region_name' => 724, 'name' => 'Liloy'],
        ['region_name' => 724, 'name' => 'Manukan'],
        ['region_name' => 724, 'name' => 'Mutia'],
        ['region_name' => 724, 'name' => 'Piñan (New Piñan)'],
        ['region_name' => 724, 'name' => 'Polanco'],
        ['region_name' => 724, 'name' => 'President Manuel A. Roxas'],
        ['region_name' => 724, 'name' => 'Rizal'],
        ['region_name' => 724, 'name' => 'Salug'],
        ['region_name' => 724, 'name' => 'Sergio Osmeña Sr.'],
        ['region_name' => 724, 'name' => 'Siayan'],
        ['region_name' => 724, 'name' => 'Sibuco'],
        ['region_name' => 724, 'name' => 'Sibutad'],
        ['region_name' => 724, 'name' => 'Sindangan'],
        ['region_name' => 724, 'name' => 'Siocon'],
        ['region_name' => 724, 'name' => 'Sirawai'],
        ['region_name' => 724, 'name' => 'Tampilisan'],
        ['region_name' => 724, 'name' => 'Aurora'],
        ['region_name' => 724, 'name' => 'Bayog'],
        ['region_name' => 724, 'name' => 'Dimataling'],
        ['region_name' => 724, 'name' => 'Dinas'],
        ['region_name' => 724, 'name' => 'Dumalinao'],
        ['region_name' => 724, 'name' => 'Dumingag'],
        ['region_name' => 724, 'name' => 'Guipos'],
        ['region_name' => 724, 'name' => 'Josefina'],
        ['region_name' => 724, 'name' => 'Kumalarang'],
        ['region_name' => 724, 'name' => 'Labangan'],
        ['region_name' => 724, 'name' => 'Lakewood'],
        ['region_name' => 724, 'name' => 'Lapuyan'],
        ['region_name' => 724, 'name' => 'Mahayag'],
        ['region_name' => 724, 'name' => 'Margosatubig'],
        ['region_name' => 724, 'name' => 'Midsalip'],
        ['region_name' => 724, 'name' => 'Molave'],
        ['region_name' => 724, 'name' => 'Pagadian City'],
        ['region_name' => 724, 'name' => 'Pitogo'],
        ['region_name' => 724, 'name' => 'Ramon Magsaysay (Liargo)'],
        ['region_name' => 724, 'name' => 'San Miguel'],
        ['region_name' => 724, 'name' => 'San Pablo'],
        ['region_name' => 724, 'name' => 'Sominot (Don Mariano Marcos)'],
        ['region_name' => 724, 'name' => 'Tabina'],
        ['region_name' => 724, 'name' => 'Tambulig'],
        ['region_name' => 724, 'name' => 'Tigbao'],
        ['region_name' => 724, 'name' => 'Tukuran'],
        ['region_name' => 724, 'name' => 'Vincenzo A. Sagun'],
        ['region_name' => 724, 'name' => 'Zamboanga City'],
        ['region_name' => 724, 'name' => 'Alicia'],
        ['region_name' => 724, 'name' => 'Buug'],
        ['region_name' => 724, 'name' => 'Diplahan'],
        ['region_name' => 724, 'name' => 'Imelda'],
        ['region_name' => 724, 'name' => 'Ipil'],
        ['region_name' => 724, 'name' => 'Kabasalan'],
        ['region_name' => 724, 'name' => 'Mabuhay'],
        ['region_name' => 724, 'name' => 'Malangas'],
        ['region_name' => 724, 'name' => 'Naga'],
        ['region_name' => 724, 'name' => 'Olutanga'],
        ['region_name' => 724, 'name' => 'Payao'],
        ['region_name' => 724, 'name' => 'Roseller Lim'],
        ['region_name' => 724, 'name' => 'Siay'],
        ['region_name' => 724, 'name' => 'Talusan'],
        ['region_name' => 724, 'name' => 'Titay'],
        ['region_name' => 724, 'name' => 'Tungawan'],
        ['region_name' => 724, 'name' => 'Akbar'],
        ['region_name' => 724, 'name' => 'Al-Barka'],
        ['region_name' => 724, 'name' => 'Hadji Mohammad Ajul'],
        ['region_name' => 724, 'name' => 'Hadji Muhtamad'],
        ['region_name' => 724, 'name' => 'Isabela City'],
        ['region_name' => 724, 'name' => 'Lamitan'],
        ['region_name' => 724, 'name' => 'Lamitan City'],
        ['region_name' => 724, 'name' => 'Lantawan'],
        ['region_name' => 724, 'name' => 'Maluso'],
        ['region_name' => 724, 'name' => 'Sumisip'],
        ['region_name' => 724, 'name' => 'Tabuan-Lasa'],
        ['region_name' => 724, 'name' => 'Tipo-Tipo'],
        ['region_name' => 724, 'name' => 'Tuburan'],
        ['region_name' => 724, 'name' => 'Ungkaya Pukan'],
        ['region_name' => 724, 'name' => 'Banguingui (Tongkil)'],
        ['region_name' => 724, 'name' => 'Hadji Panglima Tahil (Marunggas)'],
        ['region_name' => 724, 'name' => 'Indanan'],
        ['region_name' => 724, 'name' => 'Jolo'],
        ['region_name' => 724, 'name' => 'Kalingalan Caluang'],
        ['region_name' => 724, 'name' => 'Lugus'],
        ['region_name' => 724, 'name' => 'Luuk'],
        ['region_name' => 724, 'name' => 'Maimbung'],
        ['region_name' => 724, 'name' => 'Old Panamao'],
        ['region_name' => 724, 'name' => 'Omar'],
        ['region_name' => 724, 'name' => 'Pandami'],
        ['region_name' => 724, 'name' => 'Panglima Estino (New Panamao)'],
        ['region_name' => 724, 'name' => 'Pangutaran'],
        ['region_name' => 724, 'name' => 'Parang'],
        ['region_name' => 724, 'name' => 'Pata'],
        ['region_name' => 724, 'name' => 'Patikul'],
        ['region_name' => 724, 'name' => 'Siasi'],
        ['region_name' => 724, 'name' => 'Talipao'],
        ['region_name' => 724, 'name' => 'Tapul'],
        ['region_name' => 724, 'name' => 'Bongao'],
        ['region_name' => 724, 'name' => 'Languyan'],
        ['region_name' => 724, 'name' => 'Mapun (Cagayan de Tawi-Tawi)'],
        ['region_name' => 724, 'name' => 'Panglima Sugala (Balimbing)'],
        ['region_name' => 724, 'name' => 'Sapa-Sapa'],
        ['region_name' => 724, 'name' => 'Sibutu'],
        ['region_name' => 724, 'name' => 'Simunul'],
        ['region_name' => 724, 'name' => 'Sitangkai'],
        ['region_name' => 724, 'name' => 'South Ubian'],
        ['region_name' => 724, 'name' => 'Tandubas'],
        ['region_name' => 724, 'name' => 'Turtle Islands (Taganak)'],
    ];

    private $carCities = [
        ['region_name' => 725, 'name' => 'Buenavista'],
        ['region_name' => 725, 'name' => 'Butuan City'],
        ['region_name' => 725, 'name' => 'Cabadbaran City'],
        ['region_name' => 725, 'name' => 'Carmen'],
        ['region_name' => 725, 'name' => 'Jabonga'],
        ['region_name' => 725, 'name' => 'Kitcharao'],
        ['region_name' => 725, 'name' => 'Las Nieves'],
        ['region_name' => 725, 'name' => 'Magallanes'],
        ['region_name' => 725, 'name' => 'Nasipit'],
        ['region_name' => 725, 'name' => 'Remedios T. Romualdez'],
        ['region_name' => 725, 'name' => 'Santiago'],
        ['region_name' => 725, 'name' => 'Tubay'],
        ['region_name' => 725, 'name' => 'Bayugan City'],
        ['region_name' => 725, 'name' => 'Bunawan'],
        ['region_name' => 725, 'name' => 'Esperanza'],
        ['region_name' => 725, 'name' => 'La Paz'],
        ['region_name' => 725, 'name' => 'Loreto'],
        ['region_name' => 725, 'name' => 'Prosperidad'],
        ['region_name' => 725, 'name' => 'Rosario'],
        ['region_name' => 725, 'name' => 'San Francisco'],
        ['region_name' => 725, 'name' => 'San Luis'],
        ['region_name' => 725, 'name' => 'Santa Josefa'],
        ['region_name' => 725, 'name' => 'Sibagat'],
        ['region_name' => 725, 'name' => 'Talacogon'],
        ['region_name' => 725, 'name' => 'Trento'],
        ['region_name' => 725, 'name' => 'Veruela'],
        ['region_name' => 725, 'name' => 'Basilisa (Rizal)'],
        ['region_name' => 725, 'name' => 'Cagdianao'],
        ['region_name' => 725, 'name' => 'Dinagat'],
        ['region_name' => 725, 'name' => 'Libjo (Albor)'],
        ['region_name' => 725, 'name' => 'San Jose'],
        ['region_name' => 725, 'name' => 'Tubajon'],
        ['region_name' => 725, 'name' => 'Alegria'],
        ['region_name' => 725, 'name' => 'Bacuag'],
        ['region_name' => 725, 'name' => 'Burgos'],
        ['region_name' => 725, 'name' => 'Claver'],
        ['region_name' => 725, 'name' => 'Dapa'],
        ['region_name' => 725, 'name' => 'Del Carmen'],
        ['region_name' => 725, 'name' => 'General Luna'],
        ['region_name' => 725, 'name' => 'Gigaquit'],
        ['region_name' => 725, 'name' => 'Mainit'],
        ['region_name' => 725, 'name' => 'Malimono'],
        ['region_name' => 725, 'name' => 'Pilar'],
        ['region_name' => 725, 'name' => 'Placer'],
        ['region_name' => 725, 'name' => 'San Benito'],
        ['region_name' => 725, 'name' => 'San Francisco (Anao-Aon)'],
        ['region_name' => 725, 'name' => 'San Isidro'],
        ['region_name' => 725, 'name' => 'Santa Monica (Sapao)'],
        ['region_name' => 725, 'name' => 'Sison'],
        ['region_name' => 725, 'name' => 'Socorro'],
        ['region_name' => 725, 'name' => 'Surigao City'],
        ['region_name' => 725, 'name' => 'Tagana-an'],
        ['region_name' => 725, 'name' => 'Tubod'],
        ['region_name' => 725, 'name' => 'Barobo'],
        ['region_name' => 725, 'name' => 'Bayabas'],
        ['region_name' => 725, 'name' => 'Bislig City'],
        ['region_name' => 725, 'name' => 'Cagwait'],
        ['region_name' => 725, 'name' => 'Cantilan'],
        ['region_name' => 725, 'name' => 'Carrascal'],
        ['region_name' => 725, 'name' => 'Cortes'],
        ['region_name' => 725, 'name' => 'Hinatuan'],
        ['region_name' => 725, 'name' => 'Lanuza'],
        ['region_name' => 725, 'name' => 'Lianga'],
        ['region_name' => 725, 'name' => 'Lingig'],
        ['region_name' => 725, 'name' => 'Madrid'],
        ['region_name' => 725, 'name' => 'Marihatag'],
        ['region_name' => 725, 'name' => 'San Agustin'],
        ['region_name' => 725, 'name' => 'San Miguel'],
        ['region_name' => 725, 'name' => 'Tagbina'],
        ['region_name' => 725, 'name' => 'Tago'],
        ['region_name' => 725, 'name' => 'Tandag City'],
    ];

    private $nwestCities = [
        ['region_name' => 726, 'name' => 'Bacolod'],
        ['region_name' => 726, 'name' => 'Baloi'],
        ['region_name' => 726, 'name' => 'Baroy'],
        ['region_name' => 726, 'name' => 'Iligan City'],
        ['region_name' => 726, 'name' => 'Kapatagan'],
        ['region_name' => 726, 'name' => 'Kauswagan'],
        ['region_name' => 726, 'name' => 'Kolambugan'],
        ['region_name' => 726, 'name' => 'Lala'],
        ['region_name' => 726, 'name' => 'Linamon'],
        ['region_name' => 726, 'name' => 'Magsaysay'],
        ['region_name' => 726, 'name' => 'Maigo'],
        ['region_name' => 726, 'name' => 'Matungao'],
        ['region_name' => 726, 'name' => 'Munai'],
        ['region_name' => 726, 'name' => 'Nunungan'],
        ['region_name' => 726, 'name' => 'Pantao Ragat'],
        ['region_name' => 726, 'name' => 'Pantar'],
        ['region_name' => 726, 'name' => 'Poona Piagapo'],
        ['region_name' => 726, 'name' => 'Salvador'],
        ['region_name' => 726, 'name' => 'Sapad'],
        ['region_name' => 726, 'name' => 'Sultan Naga Dimaporo (Karomatan)'],
        ['region_name' => 726, 'name' => 'Tagoloan'],
        ['region_name' => 726, 'name' => 'Tangcal'],
        ['region_name' => 726, 'name' => 'Tubod'],
        ['region_name' => 726, 'name' => 'Aloran'],
        ['region_name' => 726, 'name' => 'Baliangao'],
        ['region_name' => 726, 'name' => 'Bonifacio'],
        ['region_name' => 726, 'name' => 'Calamba'],
        ['region_name' => 726, 'name' => 'Clarin'],
        ['region_name' => 726, 'name' => 'Concepcion'],
        ['region_name' => 726, 'name' => 'Don Victoriano Chiongbian (Don Mariano Marcos)'],
        ['region_name' => 726, 'name' => 'Jimenez'],
        ['region_name' => 726, 'name' => 'Lopez Jaena'],
        ['region_name' => 726, 'name' => 'Oroquieta City'],
        ['region_name' => 726, 'name' => 'Ozamiz City'],
        ['region_name' => 726, 'name' => 'Panaon'],
        ['region_name' => 726, 'name' => 'Plaridel'],
        ['region_name' => 726, 'name' => 'Sapang Dalaga'],
        ['region_name' => 726, 'name' => 'Sinacaban'],
        ['region_name' => 726, 'name' => 'Tangub City'],
        ['region_name' => 726, 'name' => 'Tudela'],
        ['region_name' => 726, 'name' => 'Alubijid'],
        ['region_name' => 726, 'name' => 'Balingasag'],
        ['region_name' => 726, 'name' => 'Balingoan'],
        ['region_name' => 726, 'name' => 'Binuangan'],
        ['region_name' => 726, 'name' => 'Amai Manabilang (Bumbaran)'],
        ['region_name' => 726, 'name' => 'Bacolod-Kalawi (Bacolod-Grande)'],
        ['region_name' => 726, 'name' => 'Balabagan'],
        ['region_name' => 726, 'name' => 'Balindong (Watu)'],
        ['region_name' => 726, 'name' => 'Bayang'],
        ['region_name' => 726, 'name' => 'Binidayan'],
        ['region_name' => 726, 'name' => 'Buadiposo-Buntong'],
        ['region_name' => 726, 'name' => 'Bubong'],
        ['region_name' => 726, 'name' => 'Butig'],
        ['region_name' => 726, 'name' => 'Calanogas'],
        ['region_name' => 726, 'name' => 'Ditsaan-Ramain'],
        ['region_name' => 726, 'name' => 'Ganassi'],
        ['region_name' => 726, 'name' => 'Kapai'],
        ['region_name' => 726, 'name' => 'Lumba-Bayabao (Maguing)'],
        ['region_name' => 726, 'name' => 'Lumbaca-Unayan'],
        ['region_name' => 726, 'name' => 'Lumbatan'],
        ['region_name' => 726, 'name' => 'Lumbayanague'],
        ['region_name' => 726, 'name' => 'Madalum'],
        ['region_name' => 726, 'name' => 'Madamba'],
        ['region_name' => 726, 'name' => 'Maguing'],
        ['region_name' => 726, 'name' => 'Malabang'],
        ['region_name' => 726, 'name' => 'Marantao'],
        ['region_name' => 726, 'name' => 'Marawi City'],
        ['region_name' => 726, 'name' => 'Marogong'],
        ['region_name' => 726, 'name' => 'Masiu'],
        ['region_name' => 726, 'name' => 'Mulondo'],
        ['region_name' => 726, 'name' => 'Pagayawan (Tatarikan)'],
        ['region_name' => 726, 'name' => 'Piagapo'],
        ['region_name' => 726, 'name' => 'Picong (Sultan Gumander)'],
        ['region_name' => 726, 'name' => 'Poona Bayabao (Gata)'],
        ['region_name' => 726, 'name' => 'Pualas'],
        ['region_name' => 726, 'name' => 'Saguiaran'],
        ['region_name' => 726, 'name' => 'Sultan Dumalondong'],
        ['region_name' => 726, 'name' => 'Tamparan'],
        ['region_name' => 726, 'name' => 'Taraka'],
        ['region_name' => 726, 'name' => 'Tubaran'],
        ['region_name' => 726, 'name' => 'Tugaya'],
    ];

    private $cenCities = [
        ['region_name' => 727, 'name' => 'Bansalan'],
        ['region_name' => 727, 'name' => 'Digos City'],
        ['region_name' => 727, 'name' => 'Hagonoy'],
        ['region_name' => 727, 'name' => 'Kiblawan'],
        ['region_name' => 727, 'name' => 'Magsaysay'],
        ['region_name' => 727, 'name' => 'Malalag'],
        ['region_name' => 727, 'name' => 'Matanao'],
        ['region_name' => 727, 'name' => 'Padada'],
        ['region_name' => 727, 'name' => 'Santa Cruz'],
        ['region_name' => 727, 'name' => 'Sulop'],
        ['region_name' => 727, 'name' => 'Don Marcelino'],
        ['region_name' => 727, 'name' => 'Jose Abad Santos (Trinidad)'],
        ['region_name' => 727, 'name' => 'Malita'],
        ['region_name' => 727, 'name' => 'Santa Maria'],
        ['region_name' => 727, 'name' => 'Sarangani'],
        ['region_name' => 727, 'name' => 'Alamada'],
        ['region_name' => 727, 'name' => 'Aleosan'],
        ['region_name' => 727, 'name' => 'Antipas'],
        ['region_name' => 727, 'name' => 'Arakan'],
        ['region_name' => 727, 'name' => 'Banisilan'],
        ['region_name' => 727, 'name' => 'Carmen'],
        ['region_name' => 727, 'name' => 'Kabacan'],
        ['region_name' => 727, 'name' => 'Kidapawan City'],
        ['region_name' => 727, 'name' => 'Libungan'],
        ['region_name' => 727, 'name' => 'Magpet'],
        ['region_name' => 727, 'name' => 'Makilala'],
        ['region_name' => 727, 'name' => 'Matalam'],
        ['region_name' => 727, 'name' => 'Midsayap'],
        ['region_name' => 727, 'name' => 'M\'lang'],
        ['region_name' => 727, 'name' => 'Pigcawayan'],
        ['region_name' => 727, 'name' => 'Pikit'],
        ['region_name' => 727, 'name' => 'President Roxas'],
        ['region_name' => 727, 'name' => 'Tulunan'],
        ['region_name' => 727, 'name' => 'Bagumbayan'],
        ['region_name' => 727, 'name' => 'Columbio'],
        ['region_name' => 727, 'name' => 'Esperanza'],
        ['region_name' => 727, 'name' => 'Isulan'],
        ['region_name' => 727, 'name' => 'Kalamansig'],
        ['region_name' => 727, 'name' => 'Lambayong (Mariano Marcos)'],
        ['region_name' => 727, 'name' => 'Lebak'],
        ['region_name' => 727, 'name' => 'Lutayan'],
        ['region_name' => 727, 'name' => 'Palimbang'],
        ['region_name' => 727, 'name' => 'Ampatuan'],
        ['region_name' => 727, 'name' => 'Barira'],
        ['region_name' => 727, 'name' => 'Buldon'],
        ['region_name' => 727, 'name' => 'Buluan'],
        ['region_name' => 727, 'name' => 'Cotabato City'],
        ['region_name' => 727, 'name' => 'Datu Abdullah Sangki'],
        ['region_name' => 727, 'name' => 'Datu Anggal Midtimbang'],
        ['region_name' => 727, 'name' => 'Datu Blah T. Sinsuat'],
        ['region_name' => 727, 'name' => 'Datu Hoffer Ampatuan'],
        ['region_name' => 727, 'name' => 'Datu Montawal (Pagagawan)'],
        ['region_name' => 727, 'name' => 'Datu Odin Sinsuat (Dinaig)'],
        ['region_name' => 727, 'name' => 'Datu Paglas'],
        ['region_name' => 727, 'name' => 'Datu Piang (Dulawan)'],
        ['region_name' => 727, 'name' => 'Datu Salibo'],
        ['region_name' => 727, 'name' => 'Datu Saudi-Ampatuan'],
        ['region_name' => 727, 'name' => 'Datu Unsay'],
        ['region_name' => 727, 'name' => 'General Salipada K. Pendatun'],
        ['region_name' => 727, 'name' => 'Guindulungan'],
        ['region_name' => 727, 'name' => 'Kabuntalan (Tumbao)'],
        ['region_name' => 727, 'name' => 'Mamasapano'],
        ['region_name' => 727, 'name' => 'Mangudadatu'],
        ['region_name' => 727, 'name' => 'Matanog'],
        ['region_name' => 727, 'name' => 'Northern Kabuntalan'],
        ['region_name' => 727, 'name' => 'Pagalungan'],
        ['region_name' => 727, 'name' => 'Paglat'],
        ['region_name' => 727, 'name' => 'Pandag'],
        ['region_name' => 727, 'name' => 'Parang'],
        ['region_name' => 727, 'name' => 'Rajah Buayan'],
        ['region_name' => 727, 'name' => 'Shariff Aguak (Maganoy)'],
        ['region_name' => 727, 'name' => 'Shariff Saydona Mustapha'],
        ['region_name' => 727, 'name' => 'South Upi'],
        ['region_name' => 727, 'name' => 'Sultan Kudarat (Nuling)'],
        ['region_name' => 727, 'name' => 'Sultan Mastura'],
        ['region_name' => 727, 'name' => 'Sultan sa Barongis (Lambayong)'],
        ['region_name' => 727, 'name' => 'Sultan Sumagka (Talitay)'],
        ['region_name' => 727, 'name' => 'Talayan'],
        ['region_name' => 727, 'name' => 'Upi'],
    ];

    private $pdvCities = [
        ['region_name' => 728, 'name' => 'Compostela'],
        ['region_name' => 728, 'name' => 'Laak (San Vicente)'],
        ['region_name' => 728, 'name' => 'Mabini (Doña Alicia)'],
        ['region_name' => 728, 'name' => 'Maco'],
        ['region_name' => 728, 'name' => 'Maragusan (San Mariano)'],
        ['region_name' => 728, 'name' => 'Mawab'],
        ['region_name' => 728, 'name' => 'Monkayo'],
        ['region_name' => 728, 'name' => 'Montevista'],
        ['region_name' => 728, 'name' => 'Nabunturan'],
        ['region_name' => 728, 'name' => 'New Bataan'],
        ['region_name' => 728, 'name' => 'Pantukan'],
        ['region_name' => 728, 'name' => 'Asuncion (Saug)'],
        ['region_name' => 728, 'name' => 'Braulio E. Dujali'],
        ['region_name' => 728, 'name' => 'Carmen'],
        ['region_name' => 728, 'name' => 'Kapalong'],
        ['region_name' => 728, 'name' => 'New Corella'],
        ['region_name' => 728, 'name' => 'Panabo City'],
        ['region_name' => 728, 'name' => 'Samal City'],
        ['region_name' => 728, 'name' => 'San Isidro'],
        ['region_name' => 728, 'name' => 'Santo Tomas'],
        ['region_name' => 728, 'name' => 'Tagum City'],
        ['region_name' => 728, 'name' => 'Talaingod'],
        ['region_name' => 728, 'name' => 'Baganga'],
        ['region_name' => 728, 'name' => 'Banaybanay'],
        ['region_name' => 728, 'name' => 'Boston'],
        ['region_name' => 728, 'name' => 'Caraga'],
        ['region_name' => 728, 'name' => 'Cateel'],
        ['region_name' => 728, 'name' => 'Governor Generoso'],
        ['region_name' => 728, 'name' => 'Lupon'],
        ['region_name' => 728, 'name' => 'Manay'],
        ['region_name' => 728, 'name' => 'Mati City'],
        ['region_name' => 728, 'name' => 'Tarragona'],
    ];

    private function transformCity ($cityArr) {
        if (!$cityArr) {
            return [];
        }

        $region = $this->regionRepository->getByColumn('name', $cityArr[0]['region_name']);

        if ($region) {
            return array_map(function ($city) use ($region) {
                return ['region_id' => $region['id'], 'name' => strToUpper($city['name'])];
            }, $cityArr);
        }

        return [];
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = array_merge(
            $this->transformCity($this->pbbrCities),
            $this->transformCity($this->pzbrCities),
            $this->transformCity($this->cbrCities),
            $this->transformCity($this->cvrCities),
            $this->transformCity($this->neabrCities),
            $this->transformCity($this->mptbrCities),
            $this->transformCity($this->ibrCities),
            $this->transformCity($this->nwgmaCities),
            $this->transformCity($this->cgmaCities),
            $this->transformCity($this->wgmaCities),
            $this->transformCity($this->egmaCities),
            $this->transformCity($this->ngmaCities),
            $this->transformCity($this->sgmaCities),
            $this->transformCity($this->qmbrCities),
            $this->transformCity($this->cbbrCities),
            $this->transformCity($this->nbbrCities),
            $this->transformCity($this->cpbrCities),
            $this->transformCity($this->lpbrCities),
            $this->transformCity($this->bmrbrCities),
            $this->transformCity($this->sbbrCities),
            $this->transformCity($this->norbrCities),
            $this->transformCity($this->nocbrCities),
            $this->transformCity($this->igbrCities),
            $this->transformCity($this->acabrCities),
            $this->transformCity($this->cvnbrCities),
            $this->transformCity($this->evlbrCities),
            $this->transformCity($this->cvsbrCities),
            $this->transformCity($this->evsbrCities),
            $this->transformCity($this->mdavCities),
            $this->transformCity($this->socCities),
            $this->transformCity($this->nminCities),
            $this->transformCity($this->zamCities),
            $this->transformCity($this->carCities),
            $this->transformCity($this->nwestCities),
            $this->transformCity($this->cenCities),
            $this->transformCity($this->pdvCities)
        );

        $this->cityRepository->createAll($cities);
    }
}
